/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-23 04:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pos.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--滚动条样式-->\r\n");
      out.write("<script src=\"../static/base/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 二维码使用 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../static/base/js/jquery.nouislider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../static/base/js/jqprint.0.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../static/base/js/jquery-migrate-1.1.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--重置滚动条样式-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $('html,body').niceScroll({\r\n");
      out.write("        cursorcolor: \"rgb(165, 171, 179)\",\r\n");
      out.write("        cursoropacitymax: 1,\r\n");
      out.write("        touchbehavior: false,\r\n");
      out.write("        cursorwidth: \"10px\",\r\n");
      out.write("        cursorborder: \"0\",\r\n");
      out.write("        cursorborderradius: \"5px\",\r\n");
      out.write("        autohidemode: false\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 主要 -->\r\n");
      out.write("<div class=\"wrapper\" style=\"position: inherit;\">\r\n");
      out.write("<!--------------- Content start ----------------->\r\n");
      out.write("    <div class=\"content-wrapper\" ng-hide=\"numA==1||numB==1||numC==1\">\r\n");
      out.write("        <div class=\"col-md-11 pageTitl\">\r\n");
      out.write("            <h2 class=\"am-ft-16 fn-left\">商品列表</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("        <!-- content info start -->\r\n");
      out.write("        <section class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- search start -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"searchType-select\">\r\n");
      out.write("                    <label class=\"fn-left titl-label\">查询类型：</label>\r\n");
      out.write("                    <label class=\"radio-inline\">\r\n");
      out.write("                        <input class=\"searchtp\" num=\"1\" type=\"radio\" name=\"searchType\" value=\"\" ng-click=\"choice($event)\" /> 按照款号查询\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label class=\"radio-inline\">\r\n");
      out.write("                        <input class=\"searchtp\" num=\"2\" type=\"radio\" name=\"searchType\" value=\"\" ng-click=\"choice($event)\" checked /> 按照品牌查询\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"productSearch productSearch-type1\">\r\n");
      out.write("                    <form class=\"form-horizontal\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label class=\"col-sm-2 control-label\">款号：</label>\r\n");
      out.write("                                    <div class=\"col-sm-10 pro-search\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"proModelid\" placeholder=\"\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 am-ft-left searchBox\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary mgr20\" ng-click=\"getStock('1')\">查询</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-default\" ng-click=\"cleaned(this)\">清空</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"productSearch productSearch-type2\">\r\n");
      out.write("                <form class=\"form-horizontal\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">品牌：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"queryBrand.brandId as queryBrand.brandName for queryBrand in queryBrands\" ng-model=\"queryBrand\" ng-change=\"getConditions()\">\r\n");
      out.write("                                        <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">年份：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"queryYear.proYear for queryYear in queryYears\" ng-model=\"year1\">\r\n");
      out.write("                                        <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">季节：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"season.proSeason for season in seasons\" ng-model=\"season1\">\r\n");
      out.write("                                        <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-2 am-ft-left searchBox\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default\" ng-click=\"cleaned(this)\">清空</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">大品类：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"gps.proGrandparentSortId as gps.grandparentSortName for gps in grandparentSorts\" ng-model=\"gps\" ng-change=\"getParentSort()\">\r\n");
      out.write("                                    <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">中品类：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"ps.proParentSortId as ps.parentSortName for ps in parentSorts\" ng-model=\"ps\" ng-change=\"getSort()\">\r\n");
      out.write("                                    <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\" class=\"col-sm-3 control-label\">小品类：</label>\r\n");
      out.write("                                <div class=\"col-sm-8 pro-search\">\r\n");
      out.write("                                    <select class=\"col-md-12\" ng-options=\"sort.proSortId as sort.sortName for sort in sorts\" ng-model=\"sort\">\r\n");
      out.write("                                    <option value=\"\">请选择</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-3 am-ft-left fn-right searchBox\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary\" ng-click=\"getStock('2')\">查询</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("                <!-- List start -->\r\n");
      out.write("                <div class=\"proList-nav\">\r\n");
      out.write("            <div class=\"proTop\">\r\n");
      out.write("                <span class=\"fn-left\">所有商品(共{{count}}条记录)</span>\r\n");
      out.write("                <button  type=\"button\" class=\"line-btn fn-right\" ng-click=\"toAddProduct()\">添加新商品</button>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form>\r\n");
      out.write("                <table width=\"100%\" class=\"mgb0 table-hover table-condensed productTable\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th colspan=\"3\" align=\"center\" valign=\"middle\" scope=\"col\">商品</th>\r\n");
      out.write("                    <th width=\"16%\" align=\"center\" valign=\"middle\" scope=\"col\">品牌</th>\r\n");
      out.write("                    <th width=\"12%\" align=\"center\" valign=\"middle\" scope=\"col\">分类</th>\r\n");
      out.write("                    <!-- <th width=\"7%\" align=\"center\" valign=\"middle\" scope=\"col\">设计师</th> -->\r\n");
      out.write("                    <th width=\"12%\" align=\"center\" valign=\"middle\" scope=\"col\">年份</th>\r\n");
      out.write("                    <th width=\"8%\" align=\"center\" valign=\"middle\" scope=\"col\">季节</th>\r\n");
      out.write("                    <!-- <th width=\"6%\" align=\"center\" valign=\"middle\" scope=\"col\">主型</th>\r\n");
      out.write("                    <th width=\"6%\" align=\"center\" valign=\"middle\" scope=\"col\">辅型</th>\r\n");
      out.write("                    <th width=\"9%\" align=\"center\" valign=\"middle\" scope=\"col\">进仓类型</th>\r\n");
      out.write("                    <th width=\"6%\" align=\"center\" valign=\"middle\" scope=\"col\">库存</th> -->\r\n");
      out.write("                    <th width=\"12%\" align=\"center\" valign=\"middle\" scope=\"col\">操作</th>\r\n");
      out.write("                    <th width=\"13%\" align=\"center\" valign=\"middle\" scope=\"col\" ng-show=\"showQrFlag\">\r\n");
      out.write("                        <div class=\"codeSize-nav\">\r\n");
      out.write("                            <strong>码上购二维码</strong><br/>\r\n");
      out.write("                            <span class=\"set-codeSize\">尺寸:<strong class=\"code-size\" ng-model=\"codeSize\">500px</strong><i class=\"fa fa-cog\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr ng-repeat=\"pro in products\">\r\n");
      out.write("                   <td width=\"2%\"><input type=\"checkbox\" class=\"code_checkbox\" ng-click=\"check()\" ng-show=\"showQrFlag\"/></td>\r\n");
      out.write("                    <td width=\"5%\">\r\n");
      out.write("                         <img ng-src=\"{{pro.proPic}}\" class=\"productImg\" title=\"{{pro.proName}}\" alt=\"{{pro.proName}}\" />\r\n");
      out.write("                   </td>\r\n");
      out.write("                    <td width=\"20%\">\r\n");
      out.write("                        <p class=\"productTitl\">{{pro.proName}}</p>\r\n");
      out.write("                        <p>款号：{{pro.proModelnum}}</p>\r\n");
      out.write("                        <p>吊牌价：￥{{pro.proPrice}}</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>{{pro.brandName}}</td>\r\n");
      out.write("                    <td>{{pro.grandparentSortName}}<br>{{pro.parentSortName}}<br>{{pro.sortName}}</td>\r\n");
      out.write("                    <!-- <td>王某某</td> -->\r\n");
      out.write("                    <td>{{pro.proYear}}</td>\r\n");
      out.write("                    <td>{{pro.proSeason}}</td>\r\n");
      out.write("                    <!-- <td>成品</td>\r\n");
      out.write("                    <td>货品</td>\r\n");
      out.write("                    <td>常规</td>\r\n");
      out.write("                    <td>10088</td> -->\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <a ng-if=\"pro.showEditType=='1'\" ng-click=\"toEditProduct(pro.proModelnum,pro)\" href=\"javascript:;\">编辑</a>\r\n");
      out.write("                        <a ng-if=\"pro.showEditType!='1'\" ng-click=\"toProductDetail(pro.proModelnum,pro)\" href=\"javascript:;\">查看详情</a>\r\n");
      out.write("                       <!--  <button type=\"button\" class=\"soldOut\">下架</button> -->\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"\" ng-show=\"showQrFlag\">\r\n");
      out.write("                        <a href=\"javascript:;\" ng-click=\"download(this)\">下载</a>\r\n");
      out.write("                        <a href=\"javascript:;\" ng-click=\"doPrint(this)\">打印</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("              <!-- List end -->\r\n");
      out.write("               <!--  <div class=\"soldOut-batch fn-left\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"\" value=\"\" />\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-default\">批量下架</button>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("                <!-- content info end -->\r\n");
      out.write("                <!-------right content end--------->\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!-------right content end--------->\r\n");
      out.write("\t    <div class=\"select-batch fn-left\" ng-show=\"showQrFlag\">\r\n");
      out.write("\t        <label class=\"radio-inline fn-left\">\r\n");
      out.write("\t            <input id=\"selectAll\" class=\"selectTp\" type=\"checkbox\" name=\"\" value=\"\" ng-click=\"selectAll()\"/>全选\r\n");
      out.write("\t        </label>\r\n");
      out.write("\t        <a href=\"javascript:;\" class=\"selectTp select-invert\" ng-click=\"reverseSelect()\">反选</a>\r\n");
      out.write("\t        <a href=\"javascript:;\" class=\"line-btn\" ng-click=\"batchDownload()\">下载选中款二维码</a>\r\n");
      out.write("\t        <a href=\"javascript:;\" class=\"line-btn\" ng-click=\"doBatchPrint()\">打印选中款二维码</a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!--分页 start-->\r\n");
      out.write("\t    <div class=\"pagelist priv-pagelist\" style=\"width: 92.5% !important;\">\r\n");
      out.write("\t    \t<div id=\"paging\"></div>    \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!--分页 end-->\r\n");
      out.write("\t    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 打印 -->\r\n");
      out.write("    <div id=\"qrCodeImgs\" style=\"display:none;\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>       \r\n");
      out.write("\r\n");
      out.write("    <!---- Content-wrapper end ---->\r\n");
      out.write("<!--商品管理添加和修改-->\r\n");
      out.write("<div class=\"default\" ng-hide=\"numA==0\" ng-init=\"numA=0\" ng-show=\"numA==1\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "addproduct.jsp", out, false);
      out.write(" \r\n");
      out.write("</div> \r\n");
      out.write("<div class=\"default\" ng-hide=\"numB==0\" ng-init=\"numB=0\" ng-show=\"numB==1\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "editproduct.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"default\" ng-hide=\"numC==0\" ng-init=\"numC=0\" ng-show=\"numC==1\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "productDetail.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 二维码尺寸选择弹窗 -->\r\n");
      out.write("<div class=\"codeSize-dialog\">\r\n");
      out.write("    <p class=\"codeSize-titl\">1000px<i class=\"fa fa-caret-down mgl5\"></i></p>\r\n");
      out.write("    <div class=\"slider-minmax1 noUi-target\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /二维码尺寸选择弹窗 -->\r\n");
      out.write("<!--商品管理添加和修改代码结束-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    //搜索方式\r\n");
      out.write("    $('.productSearch-type1').hide();\r\n");
      out.write("    \r\n");
      out.write("  //二维码尺寸滑块选择\r\n");
      out.write("    $('.set-codeSize').click(function(){\r\n");
      out.write("        $('.codeSize-dialog').toggle();\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("    function DoSaveAsIMG(proModelid) {  \r\n");
      out.write("        if (document.getElementById(\"IframeReportImg\"+proModelid).src != \"about:blank\")  \r\n");
      out.write("            document.frames[\"IframeReportImg\"+proModelid].document.execCommand(\"SaveAs\",true,\"C://Users//时爽//Downloads//123.png\");          \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t/* $('.searchtp').change(function(){\r\n");
      out.write("\t        if($(this).prop('checked') && $(this).attr('num')==1){\r\n");
      out.write("\t            $('.productSearch-type1').show();\r\n");
      out.write("\t            $('.productSearch-type2').hide();\r\n");
      out.write("\t        }else if($(this).prop('checked') && $(this).attr('num')==2 ){\r\n");
      out.write("\t            $('.productSearch-type2').show();\r\n");
      out.write("\t            $('.productSearch-type1').hide();\r\n");
      out.write("\t        }\r\n");
      out.write("\t }); */\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
