/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-29 03:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ss.inventory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class inventoryadjList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--遮罩 start-->\r\n");
      out.write("<!--  -->\r\n");
      out.write("<!--遮罩 end-->\r\n");
      out.write("\r\n");
      out.write("<!--------------- Content start ----------------->\r\n");
      out.write("<div class=\"content-wrapper\">\r\n");
      out.write("    <div class=\"col-md-11 pageTitl\">\r\n");
      out.write("        <h2 class=\"am-ft-16 fn-left\">库存调整单<span></span></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"fn-clear\"></div>\r\n");
      out.write("    <!-- search -->\r\n");
      out.write("    <div class=\"listSearch\">\r\n");
      out.write("        <form class=\"form-horizontal\" id=\"inventoryDiffForm\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-11\">\r\n");
      out.write("                    <div class=\"form-group col-md-5\" style=\"margin-left:5px ;\">\r\n");
      out.write("                        <label class=\" control-label  fn-left\" style=\"line-height: 34px;padding: 0;\">盘点单号：</label>\r\n");
      out.write("                        <div class=\"col-sm-9 pro-search\">\r\n");
      out.write("                            <input type=\"text\" name=\"inventoryId\" class=\"form-control \" style=\"height:34px\" placeholder=\"\"/>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group col-md-5\">\r\n");
      out.write("                        <label class=\" control-label fn-left\" style=\"line-height: 34px;padding: 0;\">时间：</label>\r\n");
      out.write("                        <div class=\"col-sm-10 pro-search\">\r\n");
      out.write("                            <input class=\"laydate-icon form-control\" type=\"text\" onclick=\"laydate({max: laydate.now()})\" name=\"createDate\" value=\"\" readonly=\"readonly\" placeholder=\"选择时间\" style=\"height: 34px;\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-1 am-ft-center searchBox\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn fn-left btn-primary\" ng-click=\"getInventoryDiff()\">查询</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fn-clear\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- /search -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"ManColTable col-lg-12\">\r\n");
      out.write("        <form>\r\n");
      out.write("            <div class=\"PrivTable\">\r\n");
      out.write("                <table class=\"table table-hover table-striped table-bordered\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"col\">盘点单号</th>\r\n");
      out.write("                        <th scope=\"col\">盘点时间</th>\r\n");
      out.write("                        <th scope=\"col\">库存数量</th>\r\n");
      out.write("                        <th scope=\"col\">盘点数量</th>\r\n");
      out.write("                        <th scope=\"col\">差异</th>\r\n");
      out.write("                        <th scope=\"col\">盘点人</th>\r\n");
      out.write("                        <th scope=\"col\">操作</th>\r\n");
      out.write("                    </tr>                   \r\n");
      out.write("                    <tr ng-repeat=\"inventory in inventoryDiffs\" >\n");
      out.write("                    <!--<tr ng-repeat=\"inventory in inventoryDiffs\" ng-if=\"inventory.status == 1\">-->\r\n");
      out.write("                        <td>{{inventory.inventoryId}}</td>\r\n");
      out.write("                        <td>{{inventory.createDate}}</td>\r\n");
      out.write("                        <td>{{inventory.stkNum}}</td>\r\n");
      out.write("                        <td>{{inventory.invtNum}}</td>\r\n");
      out.write("                        <td><span class=\"am-ft-red\">{{inventory.diffNum}}</span></td>\r\n");
      out.write("                        <td>{{inventory.oprName}}</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <a href=\"javasctipt:void(0);\" class=\"line-btn\" am-bg=\"blue\" data=\"{{inventory.inventoryId}},{{inventory.createDate}},{{inventory.oprName}}\" ng-click=\"viewDetail($event)\">查看详情</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("\t\t\t\t<!--分页 start-->\r\n");
      out.write("\t\t\t    <div class=\"pagelist priv-pagelist\">\r\n");
      out.write("\t\t\t    \t<div id=\"paging\"></div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <!--分页 end-->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 查看详情弹窗-->\r\n");
      out.write("<div class=\"am-dialog addColordialog createInvDialog InvDialog-max fn-hide\">\r\n");
      out.write("    <i class=\"fa fa-close closeDia\"></i>\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-header\">\r\n");
      out.write("            <h3 class=\"am-ft-center\">库存调整单</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ManColTable col-lg-12\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 mgt10\">\r\n");
      out.write("                    <label class=\"col-sm-5 control-label\">盘点时间：<span>{{createDate | date:'yyyy-MM-dd'}}</span></label>\r\n");
      out.write("                    <label class=\"col-sm-5 control-label\">盘点单号：<span>{{inventoryId}}</span></label>\r\n");
      out.write("                    <label class=\"col-sm-5 control-label\">盘点人：<span>{{userName}}</span></label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form>\r\n");
      out.write("                <div class=\"PrivTable\" style=\"max-height:300px;overflow:auto;\">\r\n");
      out.write("                    <table class=\"table table-hover table-striped table-bordered\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"col\">SKU编码</th>\r\n");
      out.write("                            <th scope=\"col\">款名</th>\r\n");
      out.write("                            <th scope=\"col\">颜色</th>\r\n");
      out.write("                            <th scope=\"col\">尺码</th>\r\n");
      out.write("                            <th scope=\"col\">库存</th>\r\n");
      out.write("                            <th scope=\"col\">盘点数</th>\r\n");
      out.write("                            <th scope=\"col\">差异</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      \t<tr ng-repeat=\"inventoryDetail in inventoryDetails\" ng-if=\"inventoryDetail.diffNum!='0'\">\r\n");
      out.write("\t                    \t<td>{{inventoryDetail.proNum}}</td>\r\n");
      out.write("\t                        <td>{{inventoryDetail.proName}}</td>\r\n");
      out.write("\t                        <td>{{inventoryDetail.proColorName}}</td>\r\n");
      out.write("\t                        <td>{{inventoryDetail.proSizeName}}</td>\r\n");
      out.write("\t                        <td>{{inventoryDetail.stkNum}}</td>                    \r\n");
      out.write("\t                        <td><i class=\"am-ft-orange\">{{inventoryDetail.invtNum}}</i></td>\r\n");
      out.write("\t                        <td><i class=\"am-ft-red\">{{inventoryDetail.diffNum}}</i></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- /查看详情弹窗-->\r\n");
      out.write("\r\n");
      out.write("<!--弹窗 start-->\r\n");
      out.write("<div class=\"am-dialog EditDialog fn-hide\">\r\n");
      out.write("    <form id=\"myform\">\r\n");
      out.write("        <div class=\"am-dialog-wrap\">\r\n");
      out.write("            <div class=\"am-dialog-header\">\r\n");
      out.write("                <h3 class=\"am-ft-center\">确定删除？</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dialogBtn am-flexbox\">\r\n");
      out.write("                <button type=\"button\" class=\"am-flexbox-item btn am-button SavEdit deletGroup\" am-bg=\"blue\">确认</button>\r\n");
      out.write("                <button type=\"button\" class=\"am-flexbox-item btn am-button\" onclick=\"Dialhide()\" am-bg=\"white\">取消</button>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<!--弹窗 end-->\r\n");
      out.write("<script>\r\n");
      out.write("    //弹窗居中\r\n");
      out.write("    $('.EditDialog,.createInvDialog').center();\r\n");
      out.write("    $('.closeDia').click(function(){\r\n");
      out.write("        $('.createInvDialog,.maskBg').hide();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
