/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-04-14 01:51:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pos.promotion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class addDiscountCardstep3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper content-wrapper-order disCountCard-content-wrapper\">\n");
      out.write("\t\t\t  \t<div class=\"col-md-11  addDiscountNav\">\n");
      out.write("\t\t\t  \t\t<div class=\"addDiscountNav3_01 fn-left\">\n");
      out.write("\t\t\t  \t\t\t<span class=\"discound_nav\">卡券信息输入</span>\n");
      out.write("\t\t\t  \t\t</div>\n");
      out.write("\t\t\t\t    <div class=\"addDiscountNav3_02\">\n");
      out.write("\t\t\t  \t\t\t<span class=\"discound_nav\">卡券数量及范围数量</span>\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <div class=\"addDiscountNav3_03\">\n");
      out.write("\t\t\t  \t\t\t<span class=\"discound_nav\">添加成功</span>\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<div class=\"col-md-11 newDisCountBox\">\n");
      out.write("\t\t<p class=\"newDisCountBoxtTitle\">卡券已成功添加</p>\n");
      out.write("\t\t\t<div class=\"addDiscountCardPreview \">\n");
      out.write("\t\t\t\t<div id=\"bgColor3\" class=\"disCountCardBox disCountCardBox2\">\n");
      out.write("\t\t\t\t\t<img class=\"disCountCardPosition\" ng-show=\"couponType=='0'\" src=\"../static/base/images/virtual.png\" />\n");
      out.write("\t\t\t\t\t<img class=\"disCountCardPosition\" ng-show=\"couponType=='1'\" src=\"../static/base/images/yhq_shiti_06.png\" />\n");
      out.write("\t\t\t\t\t<img class=\"twoCodePosition\" ng-show=\"couponType=='0'\" src=\"../static/base/images/yhq_sys_03.png\" />\n");
      out.write("\t\t\t\t\t<div class=\"disCountCardR1 disCountCardR1-1 fn-clear\">\n");
      out.write("\t\t\t\t\t\t<div class=\"fn-left disCountAmount mgr10 mgt10 addStep3_Price\" ng-show=\"amount=='1'&&couponModality=='1'\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-24\">￥</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-46\">{{fixedLimit| number:0}}</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"fn-left disCountAmount addStep3Amount  addStep3_Price\" style=\"width: 136px;\" ng-show=\"amount=='0'&&couponModality=='1'\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-24\">￥</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-34 randomLineheight\">{{randomMIn | number:0}}&nbsp;-</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-34\">{{randomMax | number:0}}</span>\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"fn-left disCountAmount disCountAmountStep addStep3_Price\"  ng-show=\"couponModality=='0'\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-46\">{{discount | number:1}}</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"am-ft-18\">折</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"fn-left  addStep3Name mgl20\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"am-ft-20 disCountCardP\">{{disCountName}}</p>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"am-ft-12 plinehight\" ng-show=\"fullAmount!='0'\">满{{fullAmount | number:0}}元使用</p>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"am-ft-12 plinehight\" ng-show=\"fullAmount=='0'\">无门槛使用</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<p class=\"mgt0\">{{activeTime}}&nbsp;00:00&nbsp;至&nbsp;{{lapsedTime}}&nbsp;24:00</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<img class=\"dctcDetailBg mgb20\" src=\"../static/base/images/yhq_bg_03.png\" />\n");
      out.write("\t\t\t\t<div class=\"descText mgl-50\">\n");
      out.write("\t\t\t\t\t<div class=\"descTextBox\"> \n");
      out.write("\t\t\t\t\t\t<span ng-if=\"memberScope=='AllPeople'\">非会员可用,</span>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"memberScope=='AllMember'\">所有会员可用,</span>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"memberScope!='AllPeople'&&memberScope!='AllMember'\">限{{memberUnionName}}{{gradeName}}会员使用</span>\n");
      out.write("\t\t\t\t\t\t<p ng-if=\"memberScope!='AllPeople'&&memberScope!='AllMember'\">\n");
      out.write("\t\t\t\t\t\t\t<span>每人限{{limitCollar}}张，</span>\n");
      out.write("\t\t\t\t\t\t\t<span ng-if=\"superposition=='n'\">不可叠加.</span>\n");
      out.write("\t\t\t\t\t\t\t<span ng-if=\"superposition=='y'\">可叠加.</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"memberScope=='AllPeople'||memberScope=='AllMember'\">每人限{{limitCollar | number:0}}张,</span>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"superposition=='n'&&(memberScope=='AllPeople'||memberScope=='allMember')\">不可叠加.</span>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"superposition=='y'&&(memberScope=='AllPeople'||memberScope=='allMember')\">可叠加.</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"descTextBoundary\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"rightCommodityBox  rightCommodityBox1 fn-clear\">\n");
      out.write("\t\t\t\t\t\t<div class=\"circleBorder\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../static/base/images/yhq_01.png\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"rightCommodityDes fn-left\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--<span ng-if=\"productScope1=='1'\">适用商品<a href=\"javascript:;\" id=\"showFrame1\" >{{countPro}}&nbsp;</a>款</span>-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"am-cursor\" ng-if=\"productScope!='AllProduct'\" ng-click=\"showFrame('1')\">适用商品<span class=\"showFrame\" >&nbsp;{{countPro}}&nbsp;</span>款</div>\n");
      out.write("\t\t\t\t\t\t\t\t<span ng-if=\"productScope=='AllProduct'\">适用所有商品</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"rightCommodityBox fn-clear\" >\n");
      out.write("\t\t\t\t\t\t<div class=\"circleBorder2\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../static/base/images/yhq_02.png\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"rightCommodityDes fn-left\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--<span ng-if=\"orgScope1=='1'\">适用门店<a href=\"javascript:;\" id=\"showFrame2\">{{countShop}}&nbsp;</a>家</span>-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"am-cursor\" ng-if=\"orgScope!='AllShop'\" ng-click=\"showFrame('2')\">适用门店<span class=\"showFrame\" >&nbsp;{{countShop}}&nbsp;</span>家</div>\n");
      out.write("\t\t\t\t\t\t\t\t<span ng-if=\"orgScope=='AllShop'\">适用所有门店</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\" fn-clear\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"faNumber\" ng-if=\"couponCount!='-1'\">发放数量：{{couponCount}}份</div>\n");
      out.write("\t\t\t\t\t<button class=\"noSubmit_btn\" ng-click=\"submitCheck('1')\">暂不提交</button>\n");
      out.write("\t\t\t\t\t<button class=\"submit_btn\" ng-click=\"submitCheck('2')\">提交审核</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\t\n");
      out.write("</div>\n");
      out.write("<!--------------- Content end ----------------->\n");
      out.write("\t<!--查看商品和门店弹框-->\n");
      out.write("\t<div class=\"AddGoodsAndStoreItem  AddGoodsAndStoreItem1 fn-clear \" ng-show=\"showtype=='1'\">\n");
      out.write("\t<!--<div id=\"proFrame\" class=\"AddGoodsAndStoreItem  AddGoodsAndStoreItem1 fn-clear fn-hide \" >-->\n");
      out.write("\t\t<div class=\"addItemTitle\">\n");
      out.write("\t\t\t<span>适用商品（{{countPro}}款）</span>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<img src=\"../static/base/images/closelogo.png\" class=\"closeProOrShop\" ng-click=\"closeProOrShop()\" />\n");
      out.write("\t\t\t\t<!--<img src=\"../static/base/images/closelogo.png\" class=\"closeProOrShop\" />-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-12 addGoodsTableBox addGoodsTableBox1\">\n");
      out.write("\t\t\t<table class=\"addGoodsTable\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"15%\">款号</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"19%\">商品名称</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"16%\">品牌</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"20%\">品类</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"10%\">年份</th>\n");
      out.write("\t\t\t\t\t<th >季节</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr ng-repeat=\"pro in products\">\n");
      out.write("\t\t\t\t\t<td>{{pro.proModelnum}}</td>\n");
      out.write("\t\t\t\t\t<td>{{pro.proName | limitTo:8}}<span ng-if=\"pro.proName.length>8\">...</span></td>\n");
      out.write("\t\t\t\t\t<td>{{pro.brandName}}</td>\n");
      out.write("\t\t\t\t\t<td>{{pro.grandparentSortName}}/{{pro.parentSortName}}/{{pro.sortName}}</td>\n");
      out.write("\t\t\t\t\t<td>{{pro.proYear}}</td>\n");
      out.write("\t\t\t\t\t<td>{{pro.proSeason}}</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"AddGoodsAndStoreItem AddGoodsAndStoreItem1 fn-clear \" ng-show=\"showtype=='2'\">\n");
      out.write("\t<!--<div id=\"shopFrame\" class=\"AddGoodsAndStoreItem AddGoodsAndStoreItem1 fn-clear fn-hide\" >-->\n");
      out.write("\t\t<div class=\"addItemTitle\">\n");
      out.write("\t\t\t<span>适用门店（{{countShop}}个）</span>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<img src=\"../static/base/images/closelogo.png\"  ng-click=\"closeProOrShop()\" />\n");
      out.write("\t\t\t\t<!--<img src=\"../static/base/images/closelogo.png\" class=\"closeProOrShop\" />-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-12 addGoodsTableBox addGoodsTableBox1\">\n");
      out.write("\t\t\t<table class=\"addGoodsTable\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th width=\"32%\">门店编号</th>\n");
      out.write("\t\t\t\t\t<th >门店名称</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr  ng-repeat=\"shop in orgList\">\n");
      out.write("\t\t\t\t\t<td>{{shop.orgId}}</td>\n");
      out.write("\t\t\t\t\t<td>{{shop.shopName}}</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-12 checkAllBar checkAllBar2\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\".maskBg\").click(function(e){\n");
      out.write("\t\t\tif(e.target.className == \"maskBg fn-hide\") {\n");
      out.write("\t\t\t\t$('.AddGoodsAndStoreItem,.maskBg').hide();\r\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
