/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-24 06:02:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.shareImages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class shareImages_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper content-wrapper-itemshow content-wrapper-itemshow2\">\n");
      out.write("\t<div class=\"col-lg-12\">\n");
      out.write("\t\t<div class=\"col-md-11 storeProBox publicImgBox\">\n");
      out.write("\t\t\t<div class=\"col-md-12 fodderMainRow fodderMainRow3\">\n");
      out.write("\t\t\t\t<!--新建文件夹-->\n");
      out.write("\t\t\t\t<div class=\"fodderMain fodderMain-default\" ng-if=\"userInfo.roleId == 1\" id=\"addFolder\" ng-click=\"addFolder()\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_addfolder.png\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\">新建文件夹</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"fodderMain\" ng-repeat=\"attr in attrList\" ng-model=\"attr\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg \" ng-click=\"getImagesList(attr.proAttrId)\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_newfolder.png\" />\n");
      out.write("\t\t\t\t\t\t<div class=\"cover\" ng-if=\"userInfo.roleId == 1\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"delete am-ft-white mgr20\" ng-click=\"delFolder(attr.proAttrId,$event)\">删除</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"\" type=\"hidden\" class=\"code_checkbox\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainInfo\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" value=\"{{attr.proAttrFilePath}}\" class=\"fodderMainTitle fodderPubEdit\" ng-model=\"attr.proAttrFilePath\" placeholder=\"\" ng-blur='updateFolder(this)' />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<!--------------- /Content end ----------------->\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
