/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2016-12-22 09:30:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "public/headpage.jsp", out, false);
      out.write("\r\n");
      out.write("<!--遮罩 start-->\r\n");
      out.write("\r\n");
      out.write("<body class=\"loginBody\">\r\n");
      out.write("<!-- Top -->\r\n");
      out.write("<div class=\"topBan\">\r\n");
      out.write("    <div class=\"content-section\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"logo\">\r\n");
      out.write("            <img class=\"img-responsive\" src=\"static/base/images/register_logo.png\" alt=\"勤易科技\" />\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /Top -->\r\n");
      out.write("<!---- Content start ---->\r\n");
      out.write("<div class=\"contentNav\" ng-app=\"register\" ng-controller=\"registerController\" style=\"padding-bottom: 50px;\">\r\n");
      out.write("    <div class=\"content-section\">\r\n");
      out.write("        <form class=\"form-horizontal\" id=\"registerForm\" >\r\n");
      out.write("            <div class=\"reg-wrap\">\r\n");
      out.write("                <div class=\"regTitl\">\r\n");
      out.write("                    <span>新帐户注册</span>\r\n");
      out.write("                    <p>已有帐户？<a href=\"login.jsp\">马上登录</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">姓 名：</label>\r\n");
      out.write("                    <div class=\"col-sm-3 needValInfo\">\r\n");
      out.write("                        <input type=\"text\" name=\"trueName\" ng-model=\"registerForm.trueName\"  class=\"form-control\" placeholder=\"请输入姓名\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">手机号：</label>\r\n");
      out.write("                    <div class=\"col-sm-3 needValInfo\">\r\n");
      out.write("                        <input type=\"text\" name=\"userName\" ng-blur=\"checkUserName()\" ng-model=\"registerForm.userName\"  class=\"form-control\" placeholder=\"请输入手机号\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"error\" ng-show=\"userNameWarn\">该用户已存在！</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group needValInfo\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">设置密码：</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" ng-model=\"registerForm.password\"  class=\"form-control\" placeholder=\"请设置密码\"  required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group needValInfo\">\r\n");
      out.write("                \t<label class=\"col-sm-2 control-label\">确认密码：</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <input type=\"password\" ng-blur=\"checkPassword()\" name=\"newPassword\" ng-model=\"registerForm.newPassword\" class=\"form-control\" placeholder=\"请确认密码\"  required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"error\" ng-show=\"repassWarn\">请确认密码保持一致！</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group needValInfo\">\r\n");
      out.write("                    <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">邮箱地址：</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <input type=\"email\" name=\"email\" ng-model=\"registerForm.email\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"请输入邮箱\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                        <div class=\"checkbox\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"checkbox\" class=\"readFlag\" id=\"readFlag\">我已阅读并同意用户协议\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-offset-2 col-sm-10 regBtn\">\r\n");
      out.write("                <button type=\"button\" ng-click=\"regist()\"  class=\"btn btn-primary\">注册</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"fn-clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!---- Content end ---->\r\n");
      out.write("\r\n");
      out.write("<!---- Foot start ---->\r\n");
      out.write("<div class=\"loginfooter\">Copyright 2016, 杭州勤易科技有限公司， 浙ICP备15019091号</div>\r\n");
      out.write("<!---- Foot end ---->\r\n");
      out.write("<!-- 尾部 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/public/footstyle.jsp", out, false);
      out.write("\r\n");
      out.write("<!---- JS ---->\r\n");
      out.write("<script src=\"register.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar formArray=[];\r\n");
      out.write("    \tformArray.push('{\"registerForm\":\"/user/addUser\"}');\r\n");
      out.write("    \tinitValidate(formArray,cas);\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
