/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-27 03:31:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.memberMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class memberAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--添加人员-->\r\n");
      out.write("\t    <!--------------- Content start ----------------->\r\n");
      out.write("    <div class=\"content-wrapper content-wrapper-commerciaInfo mgb15\">\r\n");
      out.write("        <div class=\"col-md-11 pageTitl\">\r\n");
      out.write("            <h2 class=\"am-ft-16 fn-left\">添加人员</h2>\r\n");
      out.write("            <a href=\"javascript:;\" class=\"line-btn fn-right\" ng-click=\"goBack()\">返回</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("\t\t<form id=\"memberAdd\">\r\n");
      out.write("        <div class=\"ManColTable col-lg-12\">\r\n");
      out.write("            <div class=\"commercia-info mgb20 pdl15\">\r\n");
      out.write("            \t<!-- row1 -->\r\n");
      out.write("                <!--<div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>角色类型：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group\">\r\n");
      out.write("                         <select class=\"col-md-8\" ng-model=\"addMembers.memberType\" ng-options=\"x.id as x.name for x in memberTypes\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>-->\r\n");
      out.write("                <!-- row1 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>手机号：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\">\r\n");
      out.write("                        <input type=\"text\" class=\"col-md-7 text-overflow\" name=\"\" placeholder=\"\" value=\"\" ng-model=\"addMembers.userName\" ng-blur=\"checkUserName()\"/>\r\n");
      out.write("\t                    <span class=\"error\" ng-show=\"userNameWarn\">该用户已存在！</span>\r\n");
      out.write("\t                    ");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- row2 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>初始密码：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\">\r\n");
      out.write("                        <input type=\"password\" class=\"col-md-8 text-overflow\" name=\"\" placeholder=\"\" value=\"\" ng-model=\"addMembers.password\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- row3 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>昵称：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\">\r\n");
      out.write("                        <input type=\"text\" class=\"col-md-7 text-overflow\" name=\"\" placeholder=\" \" value=\"\" ng-model=\"addMembers.trueName\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- row4 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\">邮箱：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\">\r\n");
      out.write("                        <input type=\"text\" class=\"col-md-8 text-overflow\" name=\"\" placeholder=\" \" value=\"\" ng-model=\"addMembers.email\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- row5 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>部门：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\" ng-show=\"departNameInput\">\r\n");
      out.write("                        <input type=\"text\" class=\"col-md-8 text-overflow\" name=\"departName\" placeholder=\"\" value=\"\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-9 form-group needValInfo\" ng-hide=\"departNameInput\">\r\n");
      out.write("                        <select class=\"col-md-3 mgr10\" ng-options=\"n.departId as n.departName for n in parts1\" ng-model=\"selectDepartId1\" ng-change=\"sortIdChange(selectDepartId1,1)\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">总部</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select class=\"col-md-3 mgr10\" ng-show=\"parts2.length != 0\" ng-options=\"x.departId as x.departName for x in parts2\" ng-model=\"selectDepartId2\" ng-change=\"sortIdChange(selectDepartId2,2)\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select class=\"col-md-3 mgr10\" ng-show=\"parts3.length != 0\" ng-options=\"a.departId as a.departName for a in parts3\" ng-model=\"selectDepartId3\" ng-change=\"sortIdChange(selectDepartId3,3)\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select class=\"col-md-2 mgr10\" ng-show=\"parts4.length != 0\" ng-options=\"z.departId as z.departName for z in parts4\" ng-model=\"selectDepartId4\" ng-change=\"sortIdChange(selectDepartId4,4)\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <select class=\"col-md-2 mgr10\" ng-show=\"parts5.length != 0\" ng-options=\"z.departId as z.departName for z in parts5\" ng-model=\"selectDepartId5\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- row6 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>职位：</div>\r\n");
      out.write("                    <div class=\"col-md-4 form-group needValInfo\">\r\n");
      out.write("                        <select ng-options=\"role.roleId as role.roleName for role in roles\" ng-model=\"roleId\" class=\"col-md-8\">\r\n");
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary addBrandBtn\" ng-click=\"addUser()\">确认添加</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default mgl10\" ng-click=\"goBack()\">取消</button>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
