/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-27 05:49:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.memberMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class memberMgt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!--------------- Content start ----------------->\r\n");
      out.write("    <div class=\"content-wrapper fn-clear\">\r\n");
      out.write("        <div class=\"col-md-11 pageTitl no-border\">\r\n");
      out.write("        \t<a href=\"javascript:;\" class=\"btn btn-default fn-right mgl20\" ng-show=\"showBack\" ng-click=\"gobackDpart()\">返回</a> \r\n");
      out.write("            <a href=\"javascript:;\" class=\"btn btn-primary fn-right\" ng-click=\"goToAddMember()\">添加人员</a>                \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"ManColTable col-lg-12\">\r\n");
      out.write("        \t<div class=\"saleSearch saleSearch2\">\r\n");
      out.write("        \t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group col-sm-10 mgb0\">\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t    <label class=\"nowraps-text control-label\">用户名</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-4 pl0\">\r\n");
      out.write("\t\t\t\t      <input type=\"text\" class=\"form-control mgt5\" placeholder=\"请输入手机号\" ng-model=\"username\" />\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div class=\"form-group col-sm-3\">\r\n");
      out.write("\t\t\t\t  \t <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"getUserListTB()\">查询</button>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <!--<div class=\"form-group col-sm-3\">\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t    <label class=\"nowraps-text control-label\">区域</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t      <select class=\"form-control\">\r\n");
      out.write("\t\t\t\t      \t<option>杭州</option>\r\n");
      out.write("\t\t\t\t      \t<option>武汉</option>\r\n");
      out.write("\t\t\t\t      \t<option>安徽</option>\r\n");
      out.write("\t\t\t\t      </select>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group col-sm-3\">\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t    <label class=\"nowraps-text control-label\">部门</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t      <select class=\"form-control\">\r\n");
      out.write("\t\t\t\t      \t<option>客服部</option>\r\n");
      out.write("\t\t\t\t      \t<option>美工部</option>\r\n");
      out.write("\t\t\t\t      \t<option>运营部</option>\r\n");
      out.write("\t\t\t\t      \t<option>培训部</option>\r\n");
      out.write("\t\t\t\t      </select>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>-->\t\t\t\t  \r\n");
      out.write("\t\t\t\t</form>  \r\n");
      out.write("        \t</div>\r\n");
      out.write("            <div class=\"table-responsive PrivTable storesMgt-Table\">\r\n");
      out.write("                <table class=\"table table-hover table-striped table-bordered\">\r\n");
      out.write("                    <tr ng-if=\"orgTye==6\">\r\n");
      out.write("                        <th scope=\"col\">手机号</th>\r\n");
      out.write("                        <th scope=\"col\">昵称</th>\r\n");
      out.write("                        <th scope=\"col\">邮箱</th>\n");
      out.write("                        <th scope=\"col\" >部门</th>\r\n");
      out.write("                        <th scope=\"col\">区域</th>\r\n");
      out.write("                        <th scope=\"col\">职位</th>                       \r\n");
      out.write("                        <!--<th scope=\"col\">负责商户</th>\r\n");
      out.write("                        <th scope=\"col\">已发布商品</th>\r\n");
      out.write("                        <th scope=\"col\">未发布商品</th>-->\r\n");
      out.write("                        <th scope=\"col\">操作</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-if=\"orgTye==1\">\r\n");
      out.write("                        <th scope=\"col\">手机号</th>\r\n");
      out.write("                        <th scope=\"col\">昵称</th>\r\n");
      out.write("                        <th scope=\"col\">邮箱</th>\n");
      out.write("                        <th scope=\"col\">部门</th>\n");
      out.write("                        <th scope=\"col\">区域</th>\r\n");
      out.write("                        <th scope=\"col\">职位</th>\r\n");
      out.write("                        <th scope=\"col\">操作</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-repeat=\"userlist in userList\" ng-if=\"userlist.roleId==1\">\r\n");
      out.write("                        <td class=\"am-ft-yellowgreen\">{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\n");
      out.write("                        <td style=\"text-align: left;\">{{userlist.departNameTree}}</td>\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <!--<td>&nbsp;</td>\r\n");
      out.write("                        <td>&nbsp;</td>\r\n");
      out.write("                        <td>&nbsp;</td>-->\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-repeat=\"userlist in userList\" ng-class=\"{true:'logout'}[userlist.status==2]\" ng-if=\"orgTye==6&&userlist.roleId!=1\">\r\n");
      out.write("                        <td>{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\r\n");
      out.write("                        <td style=\"text-align: left;\">{{userlist.departNameTree}}</td>\r\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <!--<td ng-if=\"userlist.status==1\"><a href=\"javascript:;\" ng-click=\"goToMemberDet(this)\">{{userlist.orgNum}}个</a></td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\"></td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==1\"><a href=\"javascript:;\" ng-click=\"goToMemberDet(this)\">{{userlist.doneProNum}}个</a></td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\"></td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==1\"><a href=\"javascript:;\" ng-click=\"goToMemberDet(this)\">{{userlist.unDoProNum}}个</a></td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\"></td>-->\r\n");
      out.write("                        <td ng-if=\"userlist.status==1\">\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"mgr5\" ng-click=\"resetPswd(userlist)\">重置密码</a>\r\n");
      out.write("                            <a href=\"javascript:;\" class=\"mgr5\" ng-click=\"goToEditMember(userlist)\">编辑</a>\r\n");
      out.write("                            <a href=\"javascript:;\" class=\"am-ft-red logoutBtn\" ng-click=\"logOut(userlist)\">注销</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\">\r\n");
      out.write("                           \t 已注销\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!--<tr ng-repeat=\"userlist in userList\" ng-if=\"userlist.roleId==3 && orgTye==6\">\r\n");
      out.write("                        <td>{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\r\n");
      out.write("                        <td>{{userlist.departName}}</td>\r\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <!--<td>{{userlist.orgName}}</td>\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                        <td><a href=\"javascript:;\" ng-click=\"resetPswd(userlist)\">重置密码</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-repeat=\"userlist in userList\" ng-class=\"{true:'logout'}[userlist.status==2]\" ng-if=\"userlist.roleId==4 && orgTye==6\">\r\n");
      out.write("                        <td>{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\r\n");
      out.write("                        <td>{{userlist.departName}}</td>\r\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <!--<td>{{userlist.orgName}}</td>\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==1\">\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"mgr5\" ng-click=\"resetPswd(userlist)\">重置密码</a>\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"am-ft-red logoutBtn\" ng-click=\"logOut(userlist)\">注销</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\">\r\n");
      out.write("                           \t 已注销\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>-->\r\n");
      out.write("                    <tr ng-repeat=\"userlist in userList\" ng-if=\"userlist.roleId==3 && orgTye==1\">\r\n");
      out.write("                        <td>{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\r\n");
      out.write("                        <td style=\"text-align: left;\">{{userlist.departName}}</td>\r\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <td>———</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-repeat=\"userlist in userList\" ng-class=\"{true:'logout'}[userlist.status==2]\" ng-if=\"userlist.roleId==4 && orgTye==1\">\r\n");
      out.write("                        <td>{{userlist.userName}}</td>\r\n");
      out.write("                        <td>{{userlist.trueName}}</td>\r\n");
      out.write("                        <td>{{userlist.email}}</td>\r\n");
      out.write("                        <td style=\"text-align: left;\">{{userlist.departName}}</td>\r\n");
      out.write("                        <td>{{userlist.departArea}}</td>\r\n");
      out.write("                        <td roleid=\"{{userlist.roleId}}\">{{userlist.roleName}}</td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==1\">\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"mgr5\" ng-click=\"resetPswd(userlist)\">重置密码</a>\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"mgr5\" ng-click=\"goToEditMember(userlist)\">编辑</a>\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"am-ft-red logoutBtn\" ng-click=\"logOut(userlist)\">注销</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td ng-if=\"userlist.status==2\">\r\n");
      out.write("                           \t 已注销\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("             <!--分页 start-->\r\n");
      out.write("\t\t     <div class=\"pagelist priv-pagelist\">\r\n");
      out.write("\t\t    \t <div id=\"pagingMem\"></div>    \r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t     \t <!--分页 end-->\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fn-clear\"></div>\r\n");
      out.write("\r\n");
      out.write("<!--删除弹窗-->\r\n");
      out.write("<div class=\"am-dialog DelDialog fn-hide\" id=\"logOutDialog2\">\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-body\">\r\n");
      out.write("            <h2 class=\"am-dialog-brief\">是否确定注销</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dialogBtn am-flexbox\">\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button confirmExecute\" am-bg=\"blue\" ng-click=\"cancellation()\">确认</button>\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button closedialog\" am-bg=\"white\">取消</button>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/删除弹窗-->\r\n");
      out.write("\r\n");
      out.write("<!--重置密码弹窗-->\r\n");
      out.write("<div class=\"am-dialog DelDialog fn-hide\" id=\"resetPwDialog\">\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-body\">\r\n");
      out.write("            <h2 class=\"am-dialog-brief\">是否确定重置密码？</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dialogBtn am-flexbox\">\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button confirmExecute\" am-bg=\"blue\" ng-click=\"resetPswdCnf()\">确认</button>\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button closedialog\" am-bg=\"white\">取消</button>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/重置密码弹窗-->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$('#logOutDialog2').center();\r\n");
      out.write("\t$('#resetPwDialog').center();\r\n");
      out.write("    $(function(){\r\n");
      out.write("        //关闭弹窗\r\n");
      out.write("        $('.closedialog').click(function(){\r\n");
      out.write("            $('#logOutDialog2,.maskBg').hide();\r\n");
      out.write("            $('#resetPwDialog').hide();\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
