/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-27 03:47:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.commercialMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class commercialInfoEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper content-forwardAdd-wrapper pb20\">\n");
      out.write("\t<div class=\"col-md-11 pageTitl\">\n");
      out.write("\t\t<h2 class=\"am-ft-16 fn-left\">修改商户</h2>\n");
      out.write("\t\t<a href=\"javascript:;\" class=\"line-btn fn-right\" ng-click=\"goback()\">返回</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<section class=\"container-fluid\">\n");
      out.write("\t\t<form id=\"merchantEditForm\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"prodet-nav\">\n");
      out.write("\t\t\t\t\t<div class=\"prodet-box\">\n");
      out.write("\t\t\t\t\t\t<!-- row1 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14 mgt25\">\n");
      out.write("\t\t\t\t\t\t\t\t<em class=\"am-ft-red mgr5\">*</em>商户logo：\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 memImg mgl0\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" ngf-select=\"uploadshopLogoa($files)\" />\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"media-object\" ng-src=\"{{orgInfo.shopLogo}}\"  width=\"80\" alt=\"请选择商户logo\" id=\"shopLogoa\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"am-ft-red note-brandAdd\">(请上传700*700以上图片，小于3M)</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- row2 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商户全称：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"shopName\" placeholder=\"\" ng-value=\"orgInfo.shopName\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- row2 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">商户简介：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"mgb0\" name=\"shopInfo\">{{orgInfo.shopInfo}}</textarea>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- row3 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">通讯地址：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3 mgr5\" ng-model=\"orgInfo.province\" name=\"province\" id=\"provinceA\" ng-change=\"shopList[0].district='';shopList[0].city='';initprovinces()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option ng-repeat=\"province in provinces\"  value=\"{{province.name}}\">{{province.name}}</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3 mgr5\" ng-model=\"orgInfo.city\" name=\"city\" id=\"cityA\" ng-change=\"shopList[0].district='';initcitys()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option ng-repeat=\"city in citys[provinceId]\" ng-selected=\"orgInfo.city==city.name\" value=\"{{city.name}}\">{{city.name}}</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3 mgr5\" ng-model=\"orgInfo.district\" name=\"district\" id=\"districtA\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\"></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option ng-repeat=\"district in districts[cityId]\" ng-selected=\"orgInfo.district==district.name\" value=\"{{district.name}}\">{{district.name}}</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!--row4-->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">详细地址：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" value=\"{{orgInfo.shopAddr}}\" name=\"shopAddr\" placeholder=\"\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- row5 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">联系人：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\"  ng-value=\"orgInfo.contacts\" name=\"contacts\" placeholder=\"\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- row6 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">联系电话：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" ng-value=\"orgInfo.shopTel\" name=\"shopTel\" placeholder=\"\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- row7 -->\n");
      out.write("\t\t\t\t\t\t<!-- row8 -->\n");
      out.write("\t\t\t\t\t\t<!-- <div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">运营人员：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-8\" name=\"userIds\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option  value=\"\">请选择</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option ng-repeat=\"user in userList\" ng-selected=\"orgInfo.userId==user.userId\" ng-value=\"user.userId\">{{user.trueName}}</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary addBrandBtn\" ng-click=\"sureToSaveEdit(orgInfo.shopLogo)\">确认修改</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default mgl10\" ng-click=\"goback()\">取消</button>\n");
      out.write("\t\t</form>\n");
      out.write("\t</section>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
