/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-06 10:16:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.commercialMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class commercialManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--商户管理主页-->\r\n");
      out.write("<!--------------- Content start ----------------->\r\n");
      out.write("<div class=\"content-wrapper content-member-wrapper sku-content-wrapper content-forward-wrapper\">\r\n");
      out.write("    <div class=\"ManColTable col-lg-12\">\r\n");
      out.write("        <div class=\"col-lg-12 pl0 pr0\">\r\n");
      out.write("            <h2 class=\"am-ft-16 fn-left color666\">商户管理（共{{count}}个商户）</h2>\r\n");
      out.write("            <a  href=\"javascript:;\" class=\"btn btn-primary fn-right\" style=\"height:28px;line-height:14px;\" ng-click=\"goRoute('commercialAdd',this)\">添加商户</a>\r\n");
      out.write("            \r\n");
      out.write("\t         <div class=\"OderlistSearch mgt0 col-md-4 fn-right\" ng-if=\"count>0\">\r\n");
      out.write("                <div class=\"col-md-12 searchBox pl0\">\r\n");
      out.write("                    <input type=\"text\" class=\"col-sm-10 mgt-8\" ng-model=\"shopName\" placeholder=\"商户名称\" value=\"\" />\r\n");
      out.write("                    <a href=\"javascript:;\" class=\"fn-left search-icon\" ng-click=\"search(shopName)\">查询</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("\t        </div>  \r\n");
      out.write("\t        <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<!--缺省-->\r\n");
      out.write("        <div class=\"col-md-12 dafaultWapper\" ng-if=\"count==0\">\r\n");
      out.write("\t\t\t<div class=\"loadingFormal\" ng-if=\"addShowFlag\">\r\n");
      out.write("\t\t\t\t<img src=\"../static/base/images/icon_notice.png\">\r\n");
      out.write("\t\t\t\t<span  style=\"font-size:16px;\">您还没有添加商户<a ng-if=\"userInfo.roleId=='13'||userInfo.roleId=='14'||userInfo.roleId=='5'\" href=\"javascript:;\" class=\"mgl10\" ng-click=\"goRoute('commercialAdd',this)\">立即添加</a></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 商户列表 -->\r\n");
      out.write("        <div class=\"col-lg-12\" style=\"padding: 0;\">\r\n");
      out.write("            <div class=\"productCenterInfo\">\r\n");
      out.write("                <table class=\"table table-hover table-striped productTable\" ng-if=\"count>0\">\r\n");
      out.write("                    <tr ng-if=\"userInfo.roleId=='1'\">\r\n");
      out.write("                        <th width=\"40%\" colspan=\"2\">商户</th>\r\n");
      out.write("                        <th width=\"10%\">全部商品</th>\r\n");
      out.write("                        <th width=\"10%\">未发布商品</th>\r\n");
      out.write("                        <th width=\"10%\">素材图片</th>\r\n");
      out.write("                        <th width=\"10%\">正式图库</th>\r\n");
      out.write("                        <th width=\"10%\" >人员</th>\r\n");
      out.write("                        <th width=\"10%\" >操作</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-if=\"userInfo.roleId=='5'\">\r\n");
      out.write("                        <th width=\"40%\" colspan=\"2\">商户</th>\r\n");
      out.write("                        <th width=\"12%\">全部商品</th>\r\n");
      out.write("                        <th width=\"12%\">未发布商品</th>\r\n");
      out.write("                        <th width=\"12%\">素材图片</th>\r\n");
      out.write("                        <th width=\"12%\">正式图库</th>\r\n");
      out.write("                        <th width=\"12%\" >操作</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-if=\"userInfo.roleId=='2'\">\r\n");
      out.write("                        <th width=\"40%\" colspan=\"2\">商户</th>\r\n");
      out.write("                        <th width=\"15%\">全部商品</th>\r\n");
      out.write("                        <th width=\"15%\">未发布商品</th>\r\n");
      out.write("                        <th width=\"15%\">素材图片</th>\r\n");
      out.write("                        <th width=\"15%\">正式图库</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <!--未分配-->\r\n");
      out.write("                    <tr ng-repeat=\"orgManage in orgManageList\" ng-model=\"orgManage\">\r\n");
      out.write("                        <td class=\"orgManageProImg\" ng-if=\"orgManage.shopLogo==''\">\r\n");
      out.write("                           <img src=\"http://static.qineasy.com/base/images/img_default_company.png\" class=\"productImg\" title=\"\" alt=\"\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"orgManageProImg\" ng-if=\"orgManage.shopLogo!=''\">\r\n");
      out.write("                           <img ng-src=\"{{orgManage.shopLogo}}\" class=\"productImg\" title=\"\" alt=\"\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"comProducInfo\">\r\n");
      out.write("                            <a href=\"javascript:;\" class=\"productTitl\" ng-click=\"goRoute('productList',this)\">{{orgManage.shopName}}</a>\r\n");
      out.write("                            <p class=\"am-ft-black\">店铺数：<a href=\"javascript:;\" ng-click=\"goRoute('commercialStore',this)\">{{orgManage.shopNum}}个</a></p>\r\n");
      out.write("                            <p>联系电话：{{orgManage.shopTel}}</p>\r\n");
      out.write("                            <p>详细地址：{{orgManage.province}}{{orgManage.city}}{{orgManage.district}}{{orgManage.shopAddr}}</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><a href=\"javascript:;\" ng-click=\"goRoute('productList',this)\">{{orgManage.allPublishNum}}个</a></td>\r\n");
      out.write("                        <td><a href=\"javascript:;\"  ng-click=\"goRoute('productList',this)\">{{orgManage.unPublishNum}}个</a></td>\r\n");
      out.write("                        <td><a href=\"javascript:;\" ng-click=\"goRoute('materiaDet',this)\">素材图片</a></td>\r\n");
      out.write("                        <td><a href=\"javascript:;\" ng-click=\"goRoute('mapDepotDet',this)\">正式图库</a></td>\r\n");
      out.write("                        <td ng-if=\"orgManage.userName==''&&userInfo.roleId=='1'\"><a href=\"javascript:;\" class=\"allotOprate\" ng-click=\"selectUser(this)\">分配</a></td>\r\n");
      out.write("                        <td ng-if=\"orgManage.userName!=''&&userInfo.roleId=='1'\">\r\n");
      out.write("                        \t<a href=\"javascript:;\" class=\"allotOprate\" ng-click=\"selectUser(this)\">分配</a>\r\n");
      out.write("                        \t<p class=\"am-ft-gray disNames\">{{orgManage.userName}}</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><a ng-if=\"userInfo.roleId=='1'||userInfo.roleId=='5'\" href=\"javascript:;\" style=\"color:#00afd4;\" ng-click=\"goRoute('commercialInfoEdit',this)\">编辑</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                 <!--分页 start-->\r\n");
      out.write("\t\t\t    <div class=\"pagelist priv-pagelist\">\r\n");
      out.write("\t\t\t    \t<div id=\"pagingMain\"></div>    \r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <!--分页 end-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /商品列表 -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"fn-clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 分配运营人员弹窗  -->\r\n");
      out.write("<!--<div class=\"am-dialog forwardMgt-Dialog fn-hide\" id=\"forwardMgt-Dialog\">\r\n");
      out.write("    <i class=\"fa fa-close closeDia\" id=\"closeDia\"></i>\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-header\">\r\n");
      out.write("            <h3>选择运营人员</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"note-Dialog\">请选择<strong>“{{selectShopName}}”</strong>的运营人员：</div>\r\n");
      out.write("        <div class=\"am-dialog-body\">\r\n");
      out.write("            <div class=\"table-responsive forwComMgt-table\">\r\n");
      out.write("                <table class=\"table table-striped addInvinfo\" style=\"max-height:300px;overflow-y:auto\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"col\" width=\"50\">&nbsp;</th>\r\n");
      out.write("                        <th scope=\"col\">手机号</th>\r\n");
      out.write("                        <th scope=\"col\">昵称</th>\r\n");
      out.write("                        <th scope=\"col\">负责商户</th>\r\n");
      out.write("                        <th scope=\"col\">已完成商品</th>\r\n");
      out.write("                        <th scope=\"col\">未完成商品</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr ng-repeat=\"user in userList\" ng-click=\"clickUser(this)\">\r\n");
      out.write("                        <td><i class=\"fa fa-line-check-white\"></i></td>\r\n");
      out.write("                        <td>{{user.telphone}}</td>\r\n");
      out.write("                        <td>{{user.trueName}}</td>\r\n");
      out.write("                        <td>{{user.orgNum}}个</td>\r\n");
      out.write("                        <td>{{user.doneProNum}}个</td>\r\n");
      out.write("                        <td>{{user.unDoProNum}}个</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"am-dialog-footer\">\r\n");
      out.write("            <a href=\"javascript:;\" class=\"btn btn-primary \" ng-click=\"doOrgManage()\">确定</a>\r\n");
      out.write("            <a href=\"javascript:;\" class=\"btn btn-default closedialog mgl20\">取消</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>-->\r\n");
      out.write("<!-- /分配运营人员弹窗  -->\r\n");
      out.write("\r\n");
      out.write("<!--删除弹窗-->\r\n");
      out.write("<div class=\"am-dialog DelDialog fn-hide\">\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-body\">\r\n");
      out.write("            <h2 class=\"am-dialog-brief\">是否确定删除</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dialogBtn am-flexbox\">\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button\" am-bg=\"blue\">确认</button>\r\n");
      out.write("            <button type=\"button\" class=\"am-flexbox-item btn am-button closedialog\" am-bg=\"white\">取消</button>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/删除弹窗-->\r\n");
      out.write("\r\n");
      out.write("<!-- 新--分配运营人员弹窗  -->\r\n");
      out.write("<div class=\"am-dialog forwardMgt-Dialog allotMemDialog fn-hide\" id=\"forwardMgt-Dialog\">\r\n");
      out.write("    <i class=\"fa fa-close closeDia\" id=\"closeDia\"></i>\r\n");
      out.write("    <div class=\"am-dialog-wrap\">\r\n");
      out.write("        <div class=\"am-dialog-header\">\r\n");
      out.write("            <h3>人员分配</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"det-top\">\r\n");
      out.write("\t\t\t<img src=\"http://static.qineasy.com/base/images/img_default_company.png\">\r\n");
      out.write("\t\t\t<h3>{{selectShopName}}</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"am-dialog-body\">\r\n");
      out.write("        \t<div class=\"dialog-top\">\r\n");
      out.write("        \t\t<select class=\"fn-left\" ng-model=\"roleIds\">\r\n");
      out.write("        \t\t\t<option value=\"\">所有人员</option>\r\n");
      out.write("        \t\t\t<option value=\"2\">运营人员</option>\n");
      out.write("        \t\t\t<option value=\"5\">商务人员</option>\r\n");
      out.write("        \t\t</select>\r\n");
      out.write("        \t\t<div class=\"searchBox fn-left\">\r\n");
      out.write("                    <input type=\"text\" class=\"fn-left \" placeholder=\"请输入姓名查询\" value=\"\" ng-model=\"userName\">\r\n");
      out.write("                    <a href=\"javascript:;\" class=\"fn-left\"  ng-click=\"getUserList()\">查询</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("            <div class=\"new-dialog-container\">\t\r\n");
      out.write("            \t<p class=\"selectednote\">已选人员：</p>\r\n");
      out.write("\t\t\t\t<ul class=\"data-list\" id=\"lList\">\r\n");
      out.write("\t\t\t\t\t<li ng-repeat=\"user in userList\" >\r\n");
      out.write("\t\t\t\t\t\t<div ng-dblclick=\"doOneAdd(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"l{{user.userId}}\" type=\"checkbox\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span>{{user.trueName}}</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>{{user.roleName}}</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fn-clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"button-box\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" name=\"button\" id=\"add\" ng-click=\"doAdd()\">添 加</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" name=\"button\" id=\"remove\" ng-click=\"doRemove()\">移 除</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"data-list\" id=\"rList\">\r\n");
      out.write("\t\t\t\t\t<li ng-repeat=\"user in userCheckList\" ng-dblclick=\"doOneRemove(this)\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"r{{user.userId}}\" type=\"checkbox\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t<span>{{user.trueName}}</span>\r\n");
      out.write("\t\t\t\t\t\t<span>{{user.roleName}}</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"fn-clear\"></div>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\t\t\t\r\n");
      out.write("\t\t\t</div>                          \r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"am-dialog-footer\">\r\n");
      out.write("            <a href=\"javascript:;\" class=\"btn btn-primary \" ng-click=\"doOrgManage()\">确认</a>\r\n");
      out.write("            <a href=\"javascript:;\" class=\"btn btn-default closedialog mgl20\">取消</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /新--分配运营人员弹窗  -->\r\n");
      out.write("\r\n");
      out.write("<!--新--分配运营人员JS\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar lList = $(\"#lList\");\r\n");
      out.write("\t\tvar llList = document.getElementById(\"lList\");\r\n");
      out.write("\t\tvar rList = $(\"#rList\");\r\n");
      out.write("\t\tvar items = $(\".data-list li\");\r\n");
      out.write("\t\tfor(var i = 0;i<items.length;i++){\r\n");
      out.write("\t\t\titems[i].onclick = itemsclick;\r\n");
      out.write("\t\t\titems[i].ondblclick = itemsdblclick;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction itemsdblclick(){\r\n");
      out.write("\t\t\tif (this.parentNode === llList) {\r\n");
      out.write("\t\t\t\trList.append(this);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlList.append(this);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction itemsclick(){\r\n");
      out.write("\t\t\tvar classname = this.className;\r\n");
      out.write("\t\t\tif(classname === \"selected\"){\r\n");
      out.write("\t\t\t\tthis.className = \"\";\r\n");
      out.write("\t\t\t\t$(this).find('input').prop('checked',false);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tthis.className=\"selected\";\r\n");
      out.write("\t\t\t\t$(this).find('input').prop('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction itemsMove(){\r\n");
      out.write("\t\t\tvar items = $(\".data-list li.selected\");\r\n");
      out.write("\t\t\tfor(var i = 0;i<items.length;i++){\r\n");
      out.write("\t\t\t\tif(this.id === \"add\"){\r\n");
      out.write("\t\t\t\t\trList.append(items[i]);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tlList.append(items[i]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".data-list li\").removeClass('selected').end().find('input').prop('checked',false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#add\").on(\"click\",itemsMove);\r\n");
      out.write("\t\t$(\"#remove\").on(\"click\",itemsMove);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
