/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-28 12:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class loginmsg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar Right Menu start -->\r\n");
      out.write("        <div class=\"navbar-custom-menu\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li id=\"orgName\" class=\"loginTime\"></li>\r\n");
      out.write("                <!-- User -->\r\n");
      out.write("                <li class=\"user user-menu\">\r\n");
      out.write("                    <a href=\"javascript:;\" class=\"dropdown-toggle lt\" data-toggle=\"dropdown\"><span id=\"trueName\"></span><i class=\"fa fa-angle-down mgl10\"></i></a>\r\n");
      out.write("                    <section class=\"dropdown-menu aside-xl animated fadeInUp\">\r\n");
      out.write("                        <section class=\"panel bg-white mgb0\">\r\n");
      out.write("                            <div class=\"list-group list-group-alt\">\r\n");
      out.write("                                <a href=\"javascript:;\" onclick=\"accountInfo()\" class=\"media list-group-item mgt0\">\r\n");
      out.write("                                    <span class=\"media-body block m-b-none\">我的资料</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"javascript:;\" onclick=\"alterPassWord()\" class=\"media list-group-item mgt0\">\r\n");
      out.write("                                    <span class=\"media-body block m-b-none\">修改密码</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- messages Menu start -->\r\n");
      out.write("                <li class=\"notifications-menu\">\r\n");
      out.write("                    <a href=\"javascript:;\" class=\"messages-info\" id=\"messages-info\">\r\n");
      out.write("                        <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                        <span class=\"badge\" id=\"msg\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Exit -->\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"top-exit\" onclick=\"loginOut()\">退出登录</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>        \t\t\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\"> \r\n");
      out.write("        \tconsole.log(window.location.href)\r\n");
      out.write("        \tfunction loginOut(){\r\n");
      out.write("        \t\twsCloseConnect();        \t\t \r\n");
      out.write("        \t\twindow.location.href=\"/\"+document.location.pathname.split('/')[1]+\"/login.jsp\";      \t\t\r\n");
      out.write("        \t}\r\n");
      out.write("        \tfunction accountInfo(){\r\n");
      out.write("        \t\tvar location=window.location.href;\r\n");
      out.write("\t\t     \tvar newlocation=location.substr(0, location.indexOf('oms/'));\r\n");
      out.write("\t\t     \tlocalStorage.menuId = \"78\";\r\n");
      out.write("\t\t  \t\tlocalStorage.menuName = \"帐户资料\";\r\n");
      out.write("\t\t\t\tlocalStorage.nodeId=\"79\";\r\n");
      out.write("\t\t     \twindow.location.href=newlocation+\"oms/public/home.jsp#/accountInfo\";\r\n");
      out.write("\t\t     \tsecMenus(390,'帐户资料');\r\n");
      out.write("\t\t     \tsecNode(355,0);\r\n");
      out.write("        \t}\r\n");
      out.write("        \t\r\n");
      out.write("        \tfunction alterPassWord(){\r\n");
      out.write("        \t\tvar location=window.location.href;\r\n");
      out.write("\t\t     \tvar newlocation=location.substr(0, location.indexOf('oms/'));\r\n");
      out.write("\t\t     \tlocalStorage.menuId = \"78\";\r\n");
      out.write("\t\t  \t\tlocalStorage.menuName = \"修改密码\";\r\n");
      out.write("\t\t\t\tlocalStorage.nodeId=\"80\";\r\n");
      out.write("\t\t     \twindow.location.href=newlocation+\"oms/public/home.jsp#/alterPassword\";\r\n");
      out.write("\t\t     \tsecMenus(391,'用户设置');\t\t     \t\r\n");
      out.write("\t\t     \tsecNode(356,0);\r\n");
      out.write("        \t}       \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t$('.user-menu').click(function(){\r\n");
      out.write("\t\t        $(this).find('i.fa').toggleClass('fa-angle-up')\r\n");
      out.write("\t\t    })\r\n");
      out.write("        \t$(function(){ \r\n");
      out.write("        \t\tvar json=$.parseJSON(localStorage.userInfo);\r\n");
      out.write("        \t\tif(json.trueName != null && json.trueName != \"\"){\r\n");
      out.write("\t        \t\t$('#trueName').text(json.trueName);\r\n");
      out.write("\t        \t\t$('#orgName').text(json.orgName);\r\n");
      out.write("        \t\t}else{\r\n");
      out.write("        \t\t\t$('#trueName').text(\"账户资料\");\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t//webstocket\r\n");
      out.write("        \t\twsConnect();\r\n");
      out.write("        \t\tif(localStorage.msgCount){\r\n");
      out.write("        \t\t\tif(parseInt(localStorage.msgCount)<10){\r\n");
      out.write("\t        \t\t\tif(parseInt(localStorage.msgCount)!=0){\r\n");
      out.write("\t        \t\t\t\t$(\"#msg\").html(localStorage.msgCount);\r\n");
      out.write("\t        \t\t\t}\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#msg\").html(\"10<em>+</em>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("        \t\t}       \t\t        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("\t\t\t\tif(localStorage.message){\r\n");
      out.write("\t\t\t\t\tvar messages=localStorage.message.split(\"|\");\r\n");
      out.write("\t\t\t\t\tfor(var k in messages){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar message=messages[k].split(\"&\");\r\n");
      out.write("\t\t\t\t\t\tvar html=[];\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<li>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<a href='javascript:;'><em class='news-time'>\"+message[1]+\"</em>\"+message[0]+\"</a>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"</li>\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#newsmsg\").after(html.join(\"\"));\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(localStorage.message2){\r\n");
      out.write("\t\t\t\t\tvar messages=localStorage.message2.split(\"|\");\r\n");
      out.write("\t\t\t\t\tfor(var k in messages){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar message=messages[k].split(\"&\");\r\n");
      out.write("\t\t\t\t\t\tvar html=[];\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<li>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<div class='panelBox'>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<em class='news-time'>\"+message[1]+\"</em>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<p>\"+message[0]+\"</p>\");\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<p><button type='button' class='btn btn-primary'>接单</button>&nbsp;\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"<button type='button' class='btn btn-default'>拒单</button></p>\");\r\n");
      out.write("\t\t\t\t\t\thtml.push(\"</li>\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#ordermsg\").after(html.join(\"\"));\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}  \r\n");
      out.write("\t\t\t\t}\t\t\t\t      \t\t  \t\t      \t\t\r\n");
      out.write("        \t})\r\n");
      out.write("        \tfunction reloadTrueName(){\r\n");
      out.write("        \t    var json=$.parseJSON(localStorage.userInfo);\r\n");
      out.write("        \t\tif(json.trueName != null && json.trueName != \"\"){\r\n");
      out.write("\t        \t\t$('#trueName').text(json.trueName);\r\n");
      out.write("\t        \t\t$('#orgName').text(json.orgName);\r\n");
      out.write("        \t\t}else{\r\n");
      out.write("        \t\t\t$('#trueName').text(\"账户资料\");\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t}\r\n");
      out.write("\t\t//一级菜单点击事件\r\n");
      out.write("\t\tfunction secMenus(id,name){\r\n");
      out.write("\t\t\tlocalStorage.menuId=id;\r\n");
      out.write("\t\t\tlocalStorage.menuName=name;\r\n");
      out.write("\t\t\t$(\"#\"+id).addClass('active').siblings().removeClass('active');   \t \t\t \r\n");
      out.write("\t \t\tloadCmenu(id,name);\r\n");
      out.write("\t \t\tpMenuName=$(\"#\"+id).find(\"span\").html();\r\n");
      out.write("\t \t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync:true,\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl:cas+\"menu/getMenusByMenu\",\r\n");
      out.write("\t\t\t\tdata : {keyParams:getKeyParams(\"{\\\"pMenuId\\\":\\\"\"+id+\"\\\"}\",keyParams),\r\n");
      out.write("\t\t\t\t\tjsonObject:getJsonObject(\"{\\\"pMenuId\\\":\\\"\"+id+\"\\\"}\")},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar menus = eval(\"(\" + data + \")\").data[\"menuList\"];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  \t});\r\n");
      out.write("\t\t}        \t\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write(" <!-- webstock -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "websocket.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
