/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-28 03:33:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.saleMgt.saleManage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class clientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--<div class=\"saleSearch\">\n");
      out.write("\t<div class=\"clientName\">\n");
      out.write("\t\t<span>客户名称：</span><input type=\"text\" placeholder=\"请输入客户名称\" />\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"clientInfo fn-clear\">\n");
      out.write("\t\t<p class=\"fn-left pdr20 mgt20\">\n");
      out.write("\t\t\t<span>地区：</span>\n");
      out.write("\t\t\t<select name=\"\" id=\"\">\n");
      out.write("\t\t\t\t<option value=\"\">全部</option>\n");
      out.write("\t\t\t\t<option value=\"\">地区</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<p class=\"fn-left pdr20 mgt20\">\n");
      out.write("\t\t\t<span>部门：</span>\n");
      out.write("\t\t\t<select name=\"\" id=\"\">\n");
      out.write("\t\t\t\t<option value=\"\">全部</option>\n");
      out.write("\t\t\t\t<option value=\"\">部门1</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<p class=\"fn-left pdr20 mgt20\">\n");
      out.write("\t\t\t<span>销售人员：</span>\n");
      out.write("\t\t\t<select name=\"\" id=\"\">\n");
      out.write("\t\t\t\t<option value=\"\">全部</option>\n");
      out.write("\t\t\t\t<option value=\"\">销售人员12</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<p class=\"fn-left mgt20\">\n");
      out.write("\t\t\t<span>状态：</span>\n");
      out.write("\t\t\t<select name=\"\" id=\"\">\n");
      out.write("\t\t\t\t<option value=\"\">全部</option>\n");
      out.write("\t\t\t\t<option value=\"\">状态1</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<p class=\"fn-left pdl15 mgt20\">\n");
      out.write("\t\t\t<button>查询</button>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("</div>-->\n");
      out.write("\n");
      out.write("<table class=\"table clientTable\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<th scope=\"col\" width=\"34%\">商户</th>\n");
      out.write("\t\t<th scope=\"col\" width=\"10%\">合同总数</th>\n");
      out.write("\t\t<th scope=\"col\" width=\"13%\">合同总金额</th>\n");
      out.write("\t\t<!--<th class=\"col-lg-1\">服务类型</th>-->\n");
      out.write("\t\t<th scope=\"col\" width=\"12%\">到期时间</th>\n");
      out.write("\t\t<th scope=\"col\" width=\"11%\">销售人员</th>\n");
      out.write("\t\t<th scope=\"col\" width=\"10%\">状态</th>\n");
      out.write("\t\t<th scope=\"col\" >操作</th>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr ng-repeat=\"shopList in shopLists track by $index\" ng-class=\"{'服务中':'inServer','已到期':'notinServer'}[shopList.status]\">\n");
      out.write("\t\t<td class=\"fn-clear pl0 pr0 pt0 pb0\">\n");
      out.write("\t\t\t<div class=\"fn-left shopLoge\">\n");
      out.write("\t\t\t\t<img ng-src=\"{{shopList.shopLogo}}\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-left shopInfo\">\n");
      out.write("\t\t\t\t<p class=\"shopNamea\"><a href=\"javascript:;\" ng-click=\"addData('saleManage','orgInfo',this.shopList,'1')\">{{shopList.shopName}}</a></p>\n");
      out.write("\t\t\t\t<p class=\"shopPhone\">\n");
      out.write("\t\t\t\t\t<span>联系电话：</span>\n");
      out.write("\t\t\t\t\t<span>{{shopList.shopTel}}</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"shopAddr\">\n");
      out.write("\t\t\t\t\t<span>{{shopList.province}}</span> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<span>{{shopList.city}}</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td class=\"deepColor\">{{shopList.contractCount}}份</td>\n");
      out.write("\t\t<td class=\"deepColor\">{{shopList.totalprice}}元</td>\n");
      out.write("\t\t<!--<td>客服托管（无字段）</td>-->\n");
      out.write("\t\t<td>\n");
      out.write("\t\t\t<span ng-if=\"shopList.enddate != ''\">{{shopList.enddate}}</span>\n");
      out.write("\t\t\t<span ng-if=\"shopList.enddate == ''\">——</span>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td>\n");
      out.write("\t\t\t<span ng-if=\"shopList.businessUserName != ''\">{{shopList.businessUserName}}</span>\t\n");
      out.write("\t\t\t<span ng-if=\"shopList.businessUserName == ''\">——</span>\t\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td >{{shopList.status}}</td>\n");
      out.write("\t\t<td><a href=\"javascript:;\" ng-click=\"addData('saleManage','orgInfo',this.shopList,'1')\">查看详情</a></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<!--<tr class=\"inServer\">\n");
      out.write("\t\t<td  class=\"fn-clear pl0 pr0 pt0 pb0\">\n");
      out.write("\t\t\t<div class=\"fn-left shopLoge\">\n");
      out.write("\t\t\t\t<img src=\"http://qineasyimg.oss.aliyuncs.com/shop-img/Logo/11629/Logo/20161025080903986.jpg\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-left shopInfo\">\n");
      out.write("\t\t\t\t<p class=\"shopNamea\">宁波枚晓服饰有限公司宁波枚晓服饰有限公司</p>\n");
      out.write("\t\t\t\t<p class=\"shopPhone\">\n");
      out.write("\t\t\t\t\t<span>联系电话：</span>\n");
      out.write("\t\t\t\t\t<span>13577554455</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"shopAddr\">\n");
      out.write("\t\t\t\t\t<span>浙江</span> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<span>杭州</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td>4份</td>\n");
      out.write("\t\t<td>8000.00元</td>\n");
      out.write("\t\t<td>客服托管</td>\n");
      out.write("\t\t<td>2016-12-22</td>\n");
      out.write("\t\t<td>李雪江</td>\n");
      out.write("\t\t<td>服务中</td>\n");
      out.write("\t\t<td>查看详情</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr class=\"inServer\">\n");
      out.write("\t\t<td  class=\"fn-clear pl0 pr0 pt0 pb0\">\n");
      out.write("\t\t\t<div class=\"fn-left shopLoge\">\n");
      out.write("\t\t\t\t<img src=\"http://qineasyimg.oss.aliyuncs.com/shop-img/Logo/11629/Logo/20161025080903986.jpg\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-left shopInfo\">\n");
      out.write("\t\t\t\t<p class=\"shopNamea\">宁波枚晓服饰有限公司宁波枚晓服饰有限公司</p>\n");
      out.write("\t\t\t\t<p class=\"shopPhone\">\n");
      out.write("\t\t\t\t\t<span>联系电话：</span>\n");
      out.write("\t\t\t\t\t<span>13577554455</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"shopAddr\">\n");
      out.write("\t\t\t\t\t<span>浙江</span> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<span>杭州</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td>4份</td>\n");
      out.write("\t\t<td>8000.00元</td>\n");
      out.write("\t\t<td>客服托管</td>\n");
      out.write("\t\t<td>2016-12-22</td>\n");
      out.write("\t\t<td>李雪江</td>\n");
      out.write("\t\t<td>服务中</td>\n");
      out.write("\t\t<td>查看详情</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr class=\"inServer\">\n");
      out.write("\t\t<td  class=\"fn-clear pl0 pr0 pt0 pb0\">\n");
      out.write("\t\t\t<div class=\"fn-left shopLoge\">\n");
      out.write("\t\t\t\t<img src=\"http://qineasyimg.oss.aliyuncs.com/shop-img/Logo/11629/Logo/20161025080903986.jpg\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-left shopInfo\">\n");
      out.write("\t\t\t\t<p class=\"shopNamea\">宁波枚晓服饰有限公司宁波枚晓服饰有限公司</p>\n");
      out.write("\t\t\t\t<p class=\"shopPhone\">\n");
      out.write("\t\t\t\t\t<span>联系电话：</span>\n");
      out.write("\t\t\t\t\t<span>13577554455</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"shopAddr\">\n");
      out.write("\t\t\t\t\t<span>浙江</span> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<span>杭州</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td>4份</td>\n");
      out.write("\t\t<td>8000.00元</td>\n");
      out.write("\t\t<td>客服托管</td>\n");
      out.write("\t\t<td>2016-12-22</td>\n");
      out.write("\t\t<td>李雪江</td>\n");
      out.write("\t\t<td>服务中</td>\n");
      out.write("\t\t<td>查看详情</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr class=\"notinServer\">\n");
      out.write("\t\t<td  class=\"fn-clear pl0 pr0 pt0 pb0\">\n");
      out.write("\t\t\t<div class=\"fn-left shopLoge\">\n");
      out.write("\t\t\t\t<img src=\"http://qineasyimg.oss.aliyuncs.com/shop-img/Logo/11629/Logo/20161025080903986.jpg\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-left shopInfo\">\n");
      out.write("\t\t\t\t<p class=\"shopNamea\">宁波枚晓服饰有限公司宁波枚晓服饰有限公司</p>\n");
      out.write("\t\t\t\t<p class=\"shopPhone\">\n");
      out.write("\t\t\t\t\t<span>联系电话：</span>\n");
      out.write("\t\t\t\t\t<span>13577554455</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"shopAddr\">\n");
      out.write("\t\t\t\t\t<span>浙江</span> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<span>杭州</span>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t<td>4份</td>\n");
      out.write("\t\t<td>8000.00元</td>\n");
      out.write("\t\t<td>客服托管</td>\n");
      out.write("\t\t<td>2016-12-22</td>\n");
      out.write("\t\t<td>李雪江</td>\n");
      out.write("\t\t<td>已到期</td>\n");
      out.write("\t\t<td>查看详情</td>\n");
      out.write("\t</tr>-->\n");
      out.write("</table>\n");
      out.write("<div class=\"pagelist priv-pagelist\">\n");
      out.write("\t<div id=\"paging2\"></div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
