/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-03 10:31:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.saleMgt.saleManage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class contractList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<table class=\"table contractTable\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<th>类型</th>\n");
      out.write("\t\t<th>合同编号</th>\n");
      out.write("\t\t<th>商户名称</th>\n");
      out.write("\t\t<th>服务区域</th>\n");
      out.write("\t\t<th>服务类型</th>\n");
      out.write("\t\t<th>产品类型</th>\n");
      out.write("\t\t<th>合同金额</th>\n");
      out.write("\t\t<th>已收金额</th>\n");
      out.write("\t\t<th>合同期限</th>\n");
      out.write("\t\t<th>签单人</th>\n");
      out.write("\t\t<th>服务状态</th>\n");
      out.write("\t\t<th>处理状态</th>\n");
      out.write("\t</tr>\n");
      out.write("\t<!--<tr  ng-repeat=\"contractList in contractLists track by $index\" ng-class=\"{'服务中':'inServer','已到期':'notinServer'}[contractList.status]\">\r\n");
      out.write("\t\t<td ><a href=\"javascript:;\" ng-click=\"contractInfo(this.contractList)\">{{contractList.contractNum}}</a></td>\r\n");
      out.write("\t\t<td class=\"deepColor\">{{contractList.shopName}}</td>\r\n");
      out.write("\t\t<td>{{contractList.totalprice}}元</td>\r\n");
      out.write("\t\t<td>{{contractList.serviceType}}</td>\r\n");
      out.write("\t\t<td>{{contractList.months}}个月</td>\r\n");
      out.write("\t\t<td>{{contractList.begindate}}至{{contractList.enddate}}</td>\r\n");
      out.write("\t\t<td class=\"deepColor\">{{contractList.payTypeName}}</td>\r\n");
      out.write("\t\t<td class=\"deepColor\">{{contractList.notPaidAmount}}</td>\r\n");
      out.write("\t\t<td class=\"deepColor\">{{contractList.userName}}</td>\r\n");
      out.write("\t\t<td class=\"status\">{{contractList.status}}</td>\r\n");
      out.write("\t</tr>-->\n");
      out.write("\t<tr class=\"inServer\" ng-repeat=\"contract in contractList track by $index\">\r\n");
      out.write("\t\t<td ng-if=\"contract.contractType=='0'\">新</td>\n");
      out.write("\t\t<td ng-if=\"contract.contractType=='1'\">续</td>\n");
      out.write("\t\t<td>{{contract.contractNum}}</td>\r\n");
      out.write("\t\t<td><a href=\"javascript:;\" ng-click=\"contractInfo(contract)\">{{contract.shopName}}</a></td>\n");
      out.write("\t\t<td>{{contract.serviceArea}}</td>\r\n");
      out.write("\t\t<td>{{contract.serviceType}}</td>\t\t\r\n");
      out.write("\t\t<td>{{contract.productType}}</td>\r\n");
      out.write("\t\t<td>{{contract.totalprice}}</td>\n");
      out.write("\t\t<td>{{contract.payAmount}}</td>\r\n");
      out.write("\t\t<td>{{contract.begindate}}至{{contract.enddate}}</td>\r\n");
      out.write("\t\t<td>{{contract.signName}}</td>\r\n");
      out.write("\t\t<td class=\"status2\" ng-if='contract.contractStatus==\"0\"'>待审核</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"1\"'>待分配</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"2\"'>待确认</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"3\"'>服务中</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"4\"'>已完成</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"5\"'>暂停</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"6\"'>已终止</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"7\"'>暂停待审批</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"8\"'>终止待审批</td>\n");
      out.write("\t\t\n");
      out.write("\t\t<td class=\"status2\" ng-if='contract.contractStatus==\"0\"'>待处理</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"1\"'>待处理</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"2\"'>待处理</td>\n");
      out.write("\t\t<td class=\"status1\" ng-if='contract.contractStatus==\"3\"'>已处理</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"4\"'>已完成</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"5\"'>暂停</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"6\"'>已终止</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"7\"'>暂停待审批</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"8\"'>终止待审批</td>\n");
      out.write("\t\t<!-- <td class=\"status2\" ng-if='contract.contractStatus>0'>{{contract.contractStatus}}</td>\n");
      out.write("\t\t<td class=\"status3\" ng-if='contract.contractStatus==\"0\"'>{{contract.contractStatus}}</td> -->\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("</table>\n");
      out.write("<div class=\"pagelist priv-pagelist\">\n");
      out.write("\t<div id=\"paging1\"></div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
