/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-06 10:25:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.productCenter.productList;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class productAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper addProductContent-wrapper\">\n");
      out.write("\t<div class=\"col-md-11 pageTitl\">\n");
      out.write("\t\t<h2 class=\"am-ft-16 fn-left\" ng-if=\"proModelid!=undefined\">修改商品</h2>\n");
      out.write("\t\t<h2 class=\"am-ft-16 fn-left\" ng-if=\"proModelid==undefined\">添加商品</h2>\n");
      out.write("\t\t<a href=\"javascript:;\" class=\"line-btn fn-right\" ng-click=\"goback()\" style=\"width:70px;\">返回</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<form id=\"addproductForm\">\n");
      out.write("\t\t<section class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"prodet-nav prodet-content\">\n");
      out.write("\t\t\t\t\t<div class=\"prodet-box\">\n");
      out.write("\t\t\t\t\t\t<!----row1---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品品类：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 form-group\" id=\"ProSorts\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3\" ng-options=\"g.sortId as g.sortName for g in item0\" ng-model=\"selectSortId0\" ng-change=\"sortIdChange(selectSortId0,1)\">\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>品类细分：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 form-group\" id=\"ProSorts\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3 mgr5\" ng-options=\"p.sortId as p.sortName for p in item1\" ng-model=\"selectSortId1\" ng-change=\"sortIdChange(selectSortId1,2)\">\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3\" ng-show=\"item2.length != 0\" ng-options=\"s.sortId as s.sortName for s in item2\" ng-model=\"selectSortId2\" ng-change=\"sortIdChange(selectSortId2,'3')\">\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-3\" ng-show=\"item3.length != 0\" ng-options=\"x.sortId as x.sortName for x in item3\" ng-model=\"selectSortId3\">\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row2---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>所属品牌：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-2 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-md-12\" ng-options=\"m.brandId as m.brandName for m in queryBrands\" ng-model=\"brandIds\" ng-change=\"changeProName(itemsSort,itemsSelectSortId)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"brandId\" value=\"{{brandIds}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"fn-block mgt10 col-sm-2\" ng-click=\"addBrand()\">+&nbsp;添加品牌</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row3---->\n");
      out.write("\t\t\t\t\t\t<!-- <div class=\"row\">\n");
      out.write("                            <div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品名称：</div>\n");
      out.write("                            <div class=\"col-md-8 form-group\">\n");
      out.write("                                <input type=\"text\" class=\"col-md-8 text-overflow\" name=\"proName\" placeholder=\"\"/>\n");
      out.write("                            </div>\n");
      out.write("                        </div> -->\n");
      out.write("\t\t\t\t\t\t<!----row4---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品款号：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-2 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"text-overflow\" name=\"proModelnum\" placeholder=\"\" ng-model=\"styleNumber\" ng-blur=\"changeProName(itemsSort,itemsSelectSortId)\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>单位：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-2 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"text-overflow\" name=\"proUom\" placeholder=\"\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row5---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品主图：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 mainPhoto\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"photoBox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"photoBg\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"files\" ngf-select=\"uploadMain($files,'mainUrl')\" value=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"\" src=\"../static/base/images/icon_upload.png\" id=\"mainUrl\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"am-ft-red\">(请上传700*700以上图片，小于3M)</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row6---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\">商品属性：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10 form-group pro-property\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--inner row1-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">年份：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"proYear\" class=\"col-md-8\" ng-model=\"proYear\" ng-change=\"changeProName(itemsSort,itemsSelectSortId)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"{{year}}\" ng-repeat=\"year in years\">{{year}}</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">季节：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"proSeason\" class=\"col-md-8\" ng-model=\"proSeason\" ng-change=\"changeProName(itemsSort,itemsSelectSortId)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"春\">春</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"夏\">夏</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"秋\">秋</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"冬\">冬</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"四季\">四季</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--inner row2-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">性别：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"proSex\" class=\"col-md-8\" ng-model=\"proSex\" ng-change=\"changeProName(itemsSort,itemsSelectSortId)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"F\">男</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"M\">女</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">波段：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"proStage\" placeholder=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--inner row3-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">系列：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"proSeries\" placeholder=\"\" ng-model=\"proSeries\" ng-blur=\"changeProName(itemsSort,itemsSelectSortId)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2 inprodet-titl am-ft-12\">风格：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"proStyle\" placeholder=\"\" ng-model=\"proStyle\" ng-blur=\"changeProName(itemsSort,itemsSelectSortId)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row6---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>吊牌价格：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-2 form-group needValInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-10 text-overflow\" name=\"proPrice\" placeholder=\"\" value=\"\" />&nbsp;元\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品名称：</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"proName\" placeholder=\"\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!----row7商品规格---->\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>商品规格：</div>\n");
      out.write("\t\t\t\t\t\t\t<!----innerrow7-1 选择颜色---->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10 form-group pro-property\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--inner row1-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-8 am-ft-12 am-ft-left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"needValInfo fn-left\">请选择本商品的所有颜色</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"fn-block fn-left mgl10\" ng-click=\"addColor()\">+&nbsp;添加颜色</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--色系Tab-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"AddproTabnav col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab-item col-md-2\" data-tab=\"\" ng-repeat=\"system in itemsColorList\" ng-click=\"getColBySys(this)\" name=\"{{system.colorSystem}}\">{{system.colorSystem}}</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--色系TabContent-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"AddproTabInfo col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"proSize-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-2\" ng-repeat=\"color in colors\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" ng-model=\"x\" ng-checked=\"isSelected(color.colorId)\" ng-click=\"chkColor(color.colorId,x,color.colorName,color.colorNum)\" name=\"colorId\" value=\"{{color.colorId}}\" id=\"cl{{color.colorId}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"cl{{color.colorId}}\">{{color.colorName}}</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"AddproTabInfo AddproTabInfo2 col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"proSize-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--选择所有尺寸-->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8 am-ft-left ProSizeTitl\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"needValInfo mgl0 fn-left\">请选择本商品的所有尺码</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"fn-block fn-left mgl10\" ng-click=\"addColor()\">+&nbsp;添加尺码</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8 productSizeSlec\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"fn-left am-ft-14\">尺码组：</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"col-md-8\" ng-options=\"c.groupId as c.groupName for c in itemsGroup\" ng-model=\"selectedGroup\" ng-change=\"groupIdChange()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"groupId\" value=\"{{selectedGroup}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 ProSize mgb0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"proSize-info\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-2\" ng-repeat=\"size in sizes\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" ng-model=\"s\" ng-checked=\"isSelectedSize(size.sizeId)\" ng-click=\"chkSize(size.sizeId,s,size.sizeName,size.sizeNum)\" name=\"sizeId\" value=\"{{size.sizeId}}\" id=\"sz{{size.sizeId}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"sz{{size.sizeId}}\">{{size.sizeName}}</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!--/色系TabContent-->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!----innerrow7-2 颜色尺寸联动---->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nowraps-text inprodet-titl\">&nbsp;</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10 form-group table-responsive corlorSizeTable\">\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" class=\"table table-condensed\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">颜色</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">尺寸</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--  <th scope=\"col\">商品条形码</th> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">商品SKU编码</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr ng-repeat=\"colors in ColorNumAndName\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>{{colors.colorName}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div ng-repeat=\"sizes in SizeNumAndName\" class=\"mgb10 color-size\">{{sizes.sizeName}}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sizeName\" value=\"{{sizes.sizeName}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <td>\n");
      out.write("\t\t                                <div ng-repeat=\"sizes in SizeNumAndName\" class=\"mgb10\">\n");
      out.write("\t\t                                \t<input id=\"{{colors.colorId+sizes.sizeId}}\" name=\"proInterbc\" type=\"text\"/>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t                                </td> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div ng-repeat=\"sizes in SizeNumAndName\" class=\"mgb10 color-size\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{{styleNumber}}{{colors.colorNum}}{{sizes.sizeNum}}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"{{colors.colorId+sizes.sizeId+'1'}}\" name=\"proInnerbc\" type=\"hidden\" value=\"{{styleNumber}}{{colors.colorNum}}{{sizes.sizeNum}}\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.row -->\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary postProInfo\" ng-click=\"saveProduct(this)\" ng-if=\"proModelid==undefined\">确认添加</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary postProInfo\" ng-click=\"updateProduct(this)\" ng-if=\"proModelid!=undefined\">保存</button>\n");
      out.write("\t\t</section>\n");
      out.write("\t</form>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("</div>\n");
      out.write("<div class=\"fn-clear\"></div>\n");
      out.write("<!--添加成功弹窗-->\n");
      out.write("<div style=\"position:fixed;top:0;left:0;width:100%;height:100%;background-color:rgba(0,0,0,0.5);z-index:99999\" ng-show=\"addSuccessDialog\">\n");
      out.write("\t<div class=\"am-dialog addProductSuccess\" >\n");
      out.write("\t\t<img class=\"statImg\" src=\"../static/base/images/icon_added.png\" />\n");
      out.write("\t\t<div class=\"am-dialog-wrap\">\n");
      out.write("\t\t\t<div class=\"am-dialog-header\">\n");
      out.write("\t\t\t\t<h3>添加商品成功！</h3>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"am-dialog-body\">\n");
      out.write("\t\t\t\t<p class=\"am-dialog-brief\">您还没有为该商品上传素材\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" class=\"mgl5\" ng-click=\"uploadMateria()\">立即上传素材</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"am-dialog-brief\">\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" class=\"line-btn fn-left mgr20\" ng-click=\"lookThisDetail()\">查看商品</a>\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" class=\"line-btn fn-left\" ng-click=\"continueToAdd()\">继续添加商品</a>\n");
      out.write("\t\t\t\t\t<em class=\"fn-clear\"></em>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p class=\"mgt25 am-dialog-brief\">\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" class=\"am-ft-gray\" ng-click=\"gobackToProList()\">返回商品列表</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/添加成功弹窗-->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$('.addProductSuccess').center();\n");
      out.write("\tfunction addBrand() {\n");
      out.write("\t\tvar location = window.location.href;\n");
      out.write("\t\tvar newlocation = location.substr(0, location.indexOf('tb/'));\n");
      out.write("\t\tlocalStorage.menuId = \"351\";\n");
      out.write("\t\tlocalStorage.menuName = \"品牌管理\";\n");
      out.write("\t\twindow.location.href = newlocation + \"tb/public/home.jsp#/brandMgt\";\n");
      out.write("\t\tsecNode(351, 0);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction addColor() {\n");
      out.write("\t\tvar location = window.location.href;\n");
      out.write("\t\tvar newlocation = location.substr(0, location.indexOf('tb/'));\n");
      out.write("\t\tlocalStorage.menuId = \"350\";\n");
      out.write("\t\tlocalStorage.menuName = \"颜色管理\";\n");
      out.write("\t\twindow.location.href = newlocation + \"tb/public/home.jsp#/color\";\n");
      out.write("\t\tsecNode(350, 0);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction addSize() {\n");
      out.write("\t\tvar location = window.location.href;\n");
      out.write("\t\tvar newlocation = location.substr(0, location.indexOf('tb/'));\n");
      out.write("\t\tlocalStorage.menuId = \"349\";\n");
      out.write("\t\tlocalStorage.menuName = \"尺码管理\";\n");
      out.write("\t\twindow.location.href = newlocation + \"tb/public/home.jsp#/size\";\n");
      out.write("\t\tsecNode(349, '尺码管理');\n");
      out.write("\t}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
