/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-07 06:14:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.storeMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class storeEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--------------- Content start ----------------->\r\n");
      out.write("<div class=\"content-wrapper\">\r\n");
      out.write("\t<div class=\"col-md-11 pageTitl\">\r\n");
      out.write("\t\t<h2 class=\"am-ft-16 fn-left\">编辑店铺</h2>\r\n");
      out.write("\t\t<a href=\"javascript:;\" class=\"line-btn fn-right\" ng-click=\"goback()\">返回</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"fn-clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"prodet-nav\">\r\n");
      out.write("\t\t\t\t<div class=\"prodet-box\">\r\n");
      out.write("\t\t\t\t\t<!-- row1 -->\r\n");
      out.write("\t\t\t\t\t<form id=\"addForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14 mgt25\">\r\n");
      out.write("\t\t\t\t\t\t\t<em class=\"am-ft-red mgr5\">*</em>类型选择：\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='2']\" class=\"selec-terrace form-group\" ng-click=\"selectType('2')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_taobao.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='3']\" class=\"selec-terrace form-group\" ng-click=\"selectType('3')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_tmall.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='4']\" class=\"selec-terrace form-group\" ng-click=\"selectType('4')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_jindong.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='0']\" class=\"selec-terrace form-group\" ng-click=\"selectType('0')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_1688.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='1']\" class=\"selec-terrace form-group\" ng-click=\"selectType('1')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_AliExpress.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div ng-class=\"{true:'selected'}[shopTypeEdit=='5']\" class=\"selec-terrace form-group\" ng-click=\"selectType('5')\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"terrace-logo\" src=\"../static/base/images/logo_amazon.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"selected-icon\" src=\"../static/base/images/icon_selected.png\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- row2 -->\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14\">店铺编号：</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-5 text-overflow\" name=\"shopNum\" ng-model=\"shopNumEdit\" placeholder=\"\" ng-value=\"shopNumEdit\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t -->\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>店铺名称：</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"shopName\" ng-model=\"shopNameEdit\" placeholder=\"\" ng-value=\"shopNameEdit\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\"></em>店铺账号：</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"\" ng-model=\"thirdUserName\" placeholder=\"\" ng-value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\"></em>店铺密码：</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 form-group needValInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"\" ng-model=\"thirdPassWord\" placeholder=\"\" ng-value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- row3 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-1 inprodet-titl am-ft-14\"><em class=\"am-ft-red mgr5\">*</em>店铺网址：</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-5 form-group needValInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-md-8 text-overflow\" name=\"shopUrl\" placeholder=\"请输入http://或https://开头的店铺网址\" ng-model=\"shopUrlEdit\" ng-value=\"shopUrlEdit\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary addBrandBtn\" ng-click=\"surEditStore()\">确认修改</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-default mgl10\" ng-click=\"goback()\">取消</button>\r\n");
      out.write("\t</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fn-clear\"></div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//类型选中效果\r\n");
      out.write("\t\t$('.selec-terrace').click(function() {\r\n");
      out.write("\t\t\t$(this).addClass('selected').siblings('.selec-terrace').removeClass('selected');\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
