/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-24 06:02:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.storeMgt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class storeMgt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<!--商户-->\n");
      out.write("<div class=\"content-wrapper fn-clear\" ng-if=\"roleType=='1'\">\n");
      out.write("\t<div class=\"col-md-11 pageTitl\">\n");
      out.write("\t\t<h2 class=\"am-ft-16 fn-left\">店铺列表({{count}})</h2>\n");
      out.write("\t\t<a href=\"javascript:;\" class=\"btn btn-primary fn-right\" ng-click=\"goRoute('storeAdd','')\">添加店铺</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<!--缺省-->\n");
      out.write("\t<div class=\"col-md-11 mgl15 dafaultWapper\" ng-if=\"count==0\">\n");
      out.write("\t\t<div class=\"loadingFormal\">\n");
      out.write("\t\t\t<img src=\"../static/base/images/icon_notice.png\">\n");
      out.write("\t\t\t<span style=\"font-size:16px;\">您还没有添加店铺<a href=\"javascript:;\" ng-click=\"goRoute('storeAdd','')\">立即添加</a></span>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"ManColTable col-lg-12\" ng-if=\"count>0\">\n");
      out.write("\t\t<form>\n");
      out.write("\t\t\t<div class=\"table-responsive PrivTable storesMgt-Table\">\n");
      out.write("\t\t\t\t<table class=\"table table-hover table-striped table-bordered\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<!-- <th scope=\"col\">编号</th> -->\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\" width=\"20%\">店铺名称</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\" width=\"35%\">店铺网址</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">状态</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">授权</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">操作</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr ng-repeat=\"shop in shopList\">\n");
      out.write("\t\t\t\t\t\t<!-- <td class=\"\">{{shop.shopNum}}</td> -->\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" style=\"display: inline;\" value=\"shop.orgId\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='2'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_taobao.png\" />\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='3'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_tmall.png\" />\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='4'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_jindong.png\" />\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='0'\" src=\"../static/base/images/icon_1688.png\" />\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='1'\" src=\"../static/base/images/icon_AliExpress.png\" />\n");
      out.write("\t\t\t\t\t\t\t<img ng-if=\"shop.shopType=='5'\" src=\"../static/base/images/icon_amazon.png\" />\n");
      out.write("\t\t\t\t\t\t\t<span class=\"miniBrand-name\">{{shop.shopName}}</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<a ng-href=\"{{shop.shopUrl}}\" class=\"webUrl text-overflow\" target=\"_blank\">{{shop.shopUrl}}</a>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td ng-if=\"shop.authInfoId==''\">未授权</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"am-ft-orange\" ng-if=\"shop.authInfoId!=''\">已授权</td>\n");
      out.write("\t\t\t\t\t\t<td ng-if=\"shop.authInfoId==''\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascrpt:;\" ng-click=\"goAuth(this)\">申请授权</a>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td ng-if=\"shop.authInfoId!=''\"></td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" ng-click=\"goRoute('storeEdit',this)\">编辑</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"mgl10 am-ft-red\" ng-click=\"deleteShop(this)\">删除</a>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/商户-->\n");
      out.write("<!--代运-->\n");
      out.write("<!--  <div class=\"content-wrapper\" ng-if=\"roleType=='2'\">\n");
      out.write("        <div class=\"ManColTable col-lg-12\" ng-if=\"count>0\">\n");
      out.write("            <div class=\"forwardTop-content fn-left\">\n");
      out.write("                <div class=\"forwardTop-left\">\n");
      out.write("                    <img ng-src=\"{{commercialInfo[0].shopLogo}}\" />\n");
      out.write("                </div>\n");
      out.write("                <div class=\"forwardTop-right\">\n");
      out.write("                    <div class=\"forwardTop-righttop\">\n");
      out.write("                        <a href=\"javascript:;\" class=\"forwardTop-rightTitl\">{{commercialInfo[0].shopName}}</a>\n");
      out.write("                        <p class=\"fn-right\">运营人员：李思思 <a href=\"javascript:;\" class=\"mgl5 allotOprate\" ng-click=\"change()\">更换</a></p>\n");
      out.write("                        <div class=\"fn-clear\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"am-ft-black\">店铺数：<a href=\"javascript:;\">{{commercialInfo[0].count}}个</a></p>\n");
      out.write("                    <p>联系电话：{{commercialInfo[0].shopTel}}</p>\n");
      out.write("                    <p>详细地址：{{commercialInfo[0].shopAddr}}</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"table-responsive PrivTable storesMgt-Table\">\n");
      out.write("                <p class=\"am-ft-14 am-ft-black mgb10\">店铺列表({{count}})</p>\n");
      out.write("                <table class=\"table table-hover table-striped table-bordered\">\n");
      out.write("                    <tr>\n");
      out.write("                        <th scope=\"col\" width=\"20%\">店铺名称</th>\n");
      out.write("                        <th scope=\"col\" width=\"35%\">店铺网址</th>\n");
      out.write("                        <th scope=\"col\">状态</th>\n");
      out.write("                        <th scope=\"col\">授权</th>\n");
      out.write("                    </tr>\n");
      out.write("                     <tr ng-repeat=\"shop in shopList\">\n");
      out.write("                            <td>\n");
      out.write("                            \t<input type=\"hidden\" value=\"shop.orgId\" />\n");
      out.write("                                <span class=\"miniBrand-name\" title=\"{{shop.shopName}}\">{{shop.shopName}}</span>\n");
      out.write("                                <img  ng-if=\"shop.shopType=='3'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_taobao.png\" />\n");
      out.write("                                <img  ng-if=\"shop.shopType=='4'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_tmall.png\" />\n");
      out.write("                                <img  ng-if=\"shop.shopType=='5'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_logo_taobao.png\" />\n");
      out.write("                                <img  ng-if=\"shop.shopType=='0'\" class=\"miniBrand-logo\" src=\"../static/base/images/icon_Alibaba.png\" />\n");
      out.write("                            </td>\n");
      out.write("                            <td><a href=\"javascript:;\" class=\"webUrl text-overflow\">{{shop.shopUrl}}</a></td>\n");
      out.write("                            <td class=\"am-ft-orange\">未授权</td>\n");
      out.write("                            <td>申请进度</td>\n");
      out.write("                    </tr>\n");
      out.write("                   \n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"fn-clear\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div> -->\n");
      out.write("<!--/代运 -->\n");
      out.write("<!--授权提示弹窗-->\n");
      out.write("<div class=\"show-depotdia\" id=\"authConfirm1\" style=\"display: none;\">\n");
      out.write("\t<div class=\"accredit-content\" id=\"authConfirm\">\n");
      out.write("\t\t<div class=\"warn\">\n");
      out.write("\t\t\t请确认店铺\n");
      out.write("\t\t\t<span>[{{AuthShopName}}]</span> 是否授权完成！\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"buttonbox fn-clear\">\n");
      out.write("\t\t\t<button class=\"yes fn-left\" ng-click=\"finishAuth()\">是</button>\n");
      out.write("\t\t\t<button class=\"no fn-left\" ng-click=\"finishAuth()\">否</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- 分配运营人员弹窗  -->\n");
      out.write("<div class=\"am-dialog forwardMgt-Dialog fn-hide\" id=\"forwardMgt-Dialog3\">\n");
      out.write("\t<i class=\"fa fa-close closeDia\" id=\"closeDia\"></i>\n");
      out.write("\t<div class=\"am-dialog-wrap\">\n");
      out.write("\t\t<div class=\"am-dialog-header\">\n");
      out.write("\t\t\t<h3>选择运营人员</h3>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"note-Dialog\">请选择<strong>“杭州勤易科技有限公司”</strong>的运营人员：</div>\n");
      out.write("\t\t<div class=\"am-dialog-body\">\n");
      out.write("\t\t\t<div class=\"table-responsive forwComMgt-table\">\n");
      out.write("\t\t\t\t<table class=\"table table-striped addInvinfo\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\" width=\"50\">&nbsp;</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">手机号</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">昵称</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">负责商户</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">已完成商品</th>\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">未完成商品</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><i class=\"fa fa-line-check-white\"></i></td>\n");
      out.write("\t\t\t\t\t\t<td>13575455021</td>\n");
      out.write("\t\t\t\t\t\t<td>张三</td>\n");
      out.write("\t\t\t\t\t\t<td>30个</td>\n");
      out.write("\t\t\t\t\t\t<td>300个</td>\n");
      out.write("\t\t\t\t\t\t<td>20个</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<!--选中效果-->\n");
      out.write("\t\t\t\t\t<tr class=\"current-operate\">\n");
      out.write("\t\t\t\t\t\t<td><i class=\"fa fa-line-check-white\"></i></td>\n");
      out.write("\t\t\t\t\t\t<td>13575455021</td>\n");
      out.write("\t\t\t\t\t\t<td>张三</td>\n");
      out.write("\t\t\t\t\t\t<td>30个</td>\n");
      out.write("\t\t\t\t\t\t<td>300个</td>\n");
      out.write("\t\t\t\t\t\t<td>20个</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><i class=\"fa fa-line-check-white\"></i></td>\n");
      out.write("\t\t\t\t\t\t<td>13575455021</td>\n");
      out.write("\t\t\t\t\t\t<td>张三</td>\n");
      out.write("\t\t\t\t\t\t<td>30个</td>\n");
      out.write("\t\t\t\t\t\t<td>300个</td>\n");
      out.write("\t\t\t\t\t\t<td>20个</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"am-dialog-footer\">\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"btn btn-default closedialog\">取消</a>\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"btn btn-primary mgl20\">确定</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- /分配运营人员弹窗  -->\n");
      out.write("<!--删除弹窗-->\n");
      out.write("<div class=\"am-dialog DelDialog fn-hide\" id=\"logOutDialog\">\n");
      out.write("\t<div class=\"am-dialog-wrap\">\n");
      out.write("\t\t<div class=\"am-dialog-body\">\n");
      out.write("\t\t\t<h2 class=\"am-dialog-brief\">是否确定删除</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"dialogBtn am-flexbox\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"am-flexbox-item btn am-button confirmExecute\" am-bg=\"blue\" ng-click=\"sureDelete()\">确认</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"am-flexbox-item btn am-button closedialog\" am-bg=\"white\" ng-click=\"concelDelete()\">取消</button>\n");
      out.write("\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/删除弹窗-->\n");
      out.write("<!-- /分配运营人员弹窗  -->\n");
      out.write("<!--申请授权-->\n");
      out.write("<div class=\"show-depotdia\" id=\"authConfirm1\" ng-show=\"showAuthorizeDialog=='show'\">\n");
      out.write("\n");
      out.write("\t<div class=\"am-dialog\" id=\"authorizeDialog\">\n");
      out.write("\t\t<div class=\"am-dialog-wrap\">\n");
      out.write("\t\t\t<div class=\"am-dialog-body\">\n");
      out.write("\t\t\t\t<h2 class=\"am-dialog-brief\">该功能正在开发中，敬请期待！</h2>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"dialogBtn am-flexbox\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"am-flexbox-item btn am-button\" ng-click=\"closeauthorizeDialog()\" am-bg=\"blue\">确认</button>\n");
      out.write("\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/申请授权-->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\t$('.closedialog').click(function() {\n");
      out.write("\t\t\t$('#authorizeDialog,.maskBg').hide();\n");
      out.write("\t\t});\n");
      out.write("\t})\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
