/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-27 03:33:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.productCenter.mapDepot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mapDepotDet_005fpub_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper content-wrapper-itemshow content-wrapper-itemshow2\">\n");
      out.write("\t<div class=\"forwardTop-content fn-left\" ng-if=\"userInfo.orgType == '6'\">\n");
      out.write("\t\t<div class=\"forwardTop-left\">\n");
      out.write("\t\t\t<img ng-src=\"{{orgInfo.shopLogo}}\" ng-if=\"orgInfo.shopLogo != '' \" />\n");
      out.write("\t\t\t<img src=\"http://static.qineasy.com/base/images/img_default_company.png\" ng-if=\"orgInfo.shopLogo == '' \" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"forwardTop-right\">\n");
      out.write("\t\t\t<div class=\"forwardTop-righttop\">\n");
      out.write("\t\t\t\t<p href=\"javascript:;\" class=\"forwardTop-rightTitl\">{{orgInfo.shopName}}</p>\n");
      out.write("\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<p class=\"am-ft-black\">\n");
      out.write("\t\t\t\t<span class=\"stores-count\">店铺数：<a href=\"javascript:;\">{{orgInfo.shopNum}}个</a></span>\n");
      out.write("\t\t\t\t<span class=\"mgl10\">运营人员：{{orgInfo.userName}}<!-- <a href=\"javascript:;\"\n");
      out.write("\t\t\t\t\t\tclass=\"mgl5 allotOprate\">更换</a> --></span>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>联系电话：{{orgInfo.shopTel}}</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<span class=\"fn-left\">详细地址：{{orgInfo.province}}{{orgInfo.city}}{{orgInfo.district}}{{orgInfo.shopAddr}}</span>\n");
      out.write("\t\t\t\t<span class=\"fn-right am-ft-gray\">商户添加时间：{{orgInfo.openDate}}</span>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"col-lg-12\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t<div class=\"col-md-11 publicImgTitle\">\n");
      out.write("\t\t\t<div class=\"col-md-11\">\n");
      out.write("\t\t\t\t<p class=\"am-ft-16 mgt10\">公用图片</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-1\">\n");
      out.write("\t\t\t\t<button class=\"whiteGroundBlueBtn mgb10\" ng-click=\"gobackByRoute()\">返回</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-md-11 storeProBox publicImgBox\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!---- 移动弹窗 ---->\n");
      out.write("\t\t\t<div class=\"handleDialog moveDialog fn-hide\">\n");
      out.write("\t\t\t\t<h3>移动到<i class=\"fa fa-close closeHandle\"></i></h3>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li ng-repeat=\"attr in attrList\" ng-click=\"moveImages(attr.proAttrId)\" ng-if=\"attr.proAttrValue == ''\"><i class=\"fa fa-folder\"></i>{{attr.proAttrFilePath}}</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!---- /移动弹窗 ---->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!---- 分享弹窗 ---->\n");
      out.write("\t\t\t<div class=\"handleDialog shareDialog fn-hide\">\n");
      out.write("\t\t\t\t<h3>分享至<i class=\"fa fa-close closeHandle\"></i></h3>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li ng-repeat=\"fol in attrListFolder\" ng-click=\"shareImages(fol.proAttrId)\"><i class=\"fa fa-folder\"></i>{{fol.proAttrFilePath}}</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!---- /分享弹窗 ---->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"col-md-12 mgb10 select-wrap\">\n");
      out.write("\t\t\t\t<label class=\"storeProLabel\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" id=\"selectAllP\" ng-click=\"selectAll('P')\" /> \n");
      out.write("\t\t\t\t<span>全选</span>\n");
      out.write("\t\t\t\t</label>\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"mgl10 mgr15\" ng-click=\"downLoadPic()\">\n");
      out.write("\t\t\t\t\t<i class=\"downLoad-icon\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_download.png\" />\n");
      out.write("\t\t\t\t\t</i> 下载\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<span class=\"divline\" ng-if=\"userInfo.orgType == '6'\" >|</span>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"morehandles\" ng-click=\"postImg('imgs',this.attr)\" ng-if=\"userInfo.orgType == '6'\"> \n");
      out.write("\t\t\t\t\t<i class=\"fa fa-send\"></i>\n");
      out.write("\t\t\t\t\t发布\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"morehandles shareHandle\" ng-click=\"getShareFolder()\"> \n");
      out.write("\t\t\t\t\t<i class=\"fa fa-share-alt\"></i>\n");
      out.write("\t\t\t\t\t共享\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"morehandles moveHandle\" ng-click=\"getMoveDialog()\"> \n");
      out.write("\t\t\t\t\t<i class=\"fa fa-exchange\"></i>\n");
      out.write("\t\t\t\t\t移动\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" class=\"morehandles am-ft-gray\"ng-if=\"userInfo.orgType == '6'\" ng-click=\"delImages()\"> \n");
      out.write("\t\t\t\t\t<i class=\"fa fa-trash\"></i>\n");
      out.write("\t\t\t\t\t删除\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-12 fodderMainRow fodderMainRow3\">\n");
      out.write("\t\t\t\t<!--新建文件夹-->\n");
      out.write("\t\t\t\t<div class=\"fodderMain fodderMain-default\" id=\"addFolder\" ng-click=\"addFolderPub()\" ng-if=\"userInfo.roleId == '1' || userInfo.roleId == '2'\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_addfolder.png\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\">新建文件夹</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--上传文件-->\n");
      out.write("\t\t\t\t<div class=\"fodderMain fodderMain-default\" id=\"addFilesPub\" ng-if=\"userInfo.roleId == '1' || userInfo.roleId == '2'\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_addimg.png\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\">上传文件</a>\n");
      out.write("\t\t\t\t\t<input type=\"file\" ngf-select=\"addFiles($files)\" ngf-multiple=\"true\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--文件夹-->\n");
      out.write("\t\t\t\t<!--<div class=\"fodderMain\"  ng-repeat=\"attr in attrList| filter:{'proAttrValue':''}\" ng-model=\"attr\" >-->\n");
      out.write("\t\t\t\t<div class=\"fodderMain\" ng-repeat=\"attr in attrList track by $index\" ng-model=\"attr\" ng-if=\"attr.proAttrValue == ''\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg \" ng-click=\"getmateriaDetPubSingle(attr.proAttrId)\">\n");
      out.write("\t\t\t\t\t\t<img src=\"http://static.qineasy.com/base/images/icon_newfolder.png\" />\n");
      out.write("\t\t\t\t\t\t<input id=\"\" type=\"hidden\" class=\"code_checkbox\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainInfo\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" value=\"{{attr.proAttrFilePath}}\" class=\"fodderMainTitle fodderPubEdit\" ng-model=\"attr.proAttrFilePath\" placeholder=\"\" ng-blur='updateFolder(this)' />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--文件-->\n");
      out.write("\t\t\t\t<!--<div class=\"fodderMain\" index=\"{{$index}}\" foldtype=\"proimg\" ng-model=\"attr\" ng-repeat=\"attr in attrList | filter:{'proAttrValue':'!'}\" id=\"material{{attr.proAttrId}}P\">-->\n");
      out.write("\t\t\t\t<div class=\"fodderMain\"  index=\"{{$index}}\" foldtype=\"proimg\" ng-model=\"attr\" ng-repeat=\"attr in attrList track by $index\" ng-if=\"attr.proAttrValue != ''\" id=\"material{{attr.proAttrId}}P\">\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainImg \" ng-click=\"doSelect(this,'P')\">\n");
      out.write("\t\t\t\t\t\t<img ng-src=\"{{attr.proAttrValue}}\" />\n");
      out.write("\t\t\t\t\t\t<div class=\"cover\" ng-if=\"userInfo.orgType == '1'\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"scan am-ft-white a-dis\">预览</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"am-ft-white a-dis\" ng-click=\"downloadone(this.attr)\">下载</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cover\" ng-if=\"userInfo.orgType == '6'\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"scan am-ft-white mgr20\" ng-click=\"$event.stoppropagation()\">预览</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"am-ft-white mgr20\" ng-click=\"downloadone(this.attr)\">下载</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"delete am-ft-white\" ng-click=\"postImg('img',this.attr)\">发布</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"materialcheck{{attr.proAttrId}}P\" type=\"checkbox\" class=\"code_checkbox\" ng-show=\"false\" />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t\t\t\t<input id=\"\" type=\"hidden\" class=\"code_checkbox\" />\n");
      out.write("\t\t\t\t\t<div class=\"fodderMainInfo\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" value=\"{{attr.proAttrFilePath}}\" class=\"fodderMainTitle fodderPubEdit\" ng-model=\"attr.proAttrFilePath\" placeholder=\"\" ng-blur='updateFolder(this)' />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--分页 start-->\n");
      out.write("\t\t<div class=\"pagelist priv-pagelist\">\n");
      out.write("\t\t\t<div id=\"pagingPub\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--分页 end-->\n");
      out.write("\t\t<!--<div class=\"fn-clear\"></div>-->\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<!--------------- /Content end ----------------->\n");
      out.write("</div>\n");
      out.write("<!--授权提示弹窗-->\n");
      out.write("<div class=\"show-depotdia\" style=\"display: none;\">\n");
      out.write("\t<div class=\"accredit-content\">\n");
      out.write("\t\t<div class=\"warn\">\n");
      out.write("\t\t\t请确认店铺\n");
      out.write("\t\t\t<span>[小悠悠服饰]</span> 是否授权完成！\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"buttonbox fn-clear\">\n");
      out.write("\t\t\t<button class=\"yes fn-left\">是</button>\n");
      out.write("\t\t\t<button class=\"no fn-left\">否</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--授权提示弹窗-->\n");
      out.write("<!--发布商品弹窗-->\n");
      out.write("<!--发布商品弹框-->\n");
      out.write("<div class=\"show-depotdia\" ng-show=\"depotdia=='show'\">\n");
      out.write("\t<div class=\"setDayTargeta fn-clear pb20\" id=\"depotdia\">\n");
      out.write("\t\t<div class=\"setDayTargetTitle publishTitle fn-clear\">\n");
      out.write("\t\t\t<p class=\"fn-left\">请选择要发布的店铺</p>\n");
      out.write("\t\t\t<img class=\"closeDia fn-right\" ng-click=\"closePostDia('depotdia')\" src=\"http://static.qineasy.com/base/images/closelogo.png\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"setDayTargetContent\">\n");
      out.write("\t\t\t<div class=\"allStoreName fn-clear\" style=\"border: none;overflow: initial;\">\n");
      out.write("\t\t\t\t<div ng-click=\"postImgAlbum(this.x)\" ng-repeat=\"x in publishInfoList\" class=\"poststore\" ng-if=\"x.authInfoId != ''\">\n");
      out.write("\t\t\t\t\t<div class=\"storeName selec-stores {{x.orgId}}\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"{{x.orgId}}\" />\n");
      out.write("\t\t\t\t\t\t<span>{{x.shopName}}</span>\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType == 4\" src=\"../static/base/images/icon_logo_tmall.png\" />\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType == 3\" src=\"../static/base/images/icon_logo_taobao.png\" />\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType == 5\" src=\"../static/base/images/icon_logo_jindong.png\" />\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType=='0'\" src=\"../static/base/images/icon_1688.png\" />\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType=='1'\" src=\"../static/base/images/icon_AliExpress.png\" />\n");
      out.write("\t\t\t\t\t\t<img ng-if=\"x.shopType=='2'\" src=\"../static/base/images/icon_amazon.png\" />\n");
      out.write("\t\t\t\t\t\t<img src=\"../static/base/images/icon_selected.png\" class=\"iconSelect fn-hide\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--发布商品弹窗-->\n");
      out.write("<!--选择发布的相册-->\n");
      out.write("<div class=\"show-depotdia\" ng-show=\"album_dia=='show'\">\n");
      out.write("\t<div class=\"album-dia publishPro\" id=\"album_dia\">\n");
      out.write("\t\t<div class=\"setDayTargetTitle publishTitle fn-clear\">\n");
      out.write("\t\t\t<p class=\"fn-left\">选择发布的相册({{postshopName}})</p>\n");
      out.write("\t\t\t<img class=\"closeDia fn-right\" src=\"http://static.qineasy.com/base/images/closelogo.png\" ng-click=\"closePostDia('album_dia')\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"album-dia-content fn-clear\">\n");
      out.write("\t\t\t<div class=\"album-dia-left fn-left\" style=\"overflow-y:auto;\">\n");
      out.write("\t\t\t\t<h1>相册目录</h1>\n");
      out.write("\t\t\t\t<!----- tree start ---->\n");
      out.write("\t\t\t\t<div class=\"content_wrap\">\n");
      out.write("\t\t\t\t\t<div class=\"zTreeDemoBackground left\">\n");
      out.write("\t\t\t\t\t\t<ul id=\"treeDemo\" class=\"ztree\"></ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--<div id=\"rMenu\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li id=\"m_add\" onclick=\"addTreeNode();\">增加节点</li>\n");
      out.write("\t\t\t\t\t\t<li id=\"m_del\" onclick=\"removeTreeNode();\">删除节点</li>\n");
      out.write("\t\t\t\t\t\t<li id=\"m_check\" onclick=\"checkTreeNode(true);\">Check节点</li>\n");
      out.write("\t\t\t\t\t\t<li id=\"m_unCheck\" onclick=\"checkTreeNode(false);\">unCheck节点</li>\n");
      out.write("\t\t\t\t\t\t<li id=\"m_reset\" onclick=\"resetTree();\">恢复zTree</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t<!--右键菜单 end-->\n");
      out.write("\t\t\t\t<!----- tree end ----->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"album-dia-right fn-left\">\n");
      out.write("\t\t\t\t<div class=\"dia-right-top fn-clear\">\n");
      out.write("\t\t\t\t\t<div class=\"bread-path fn-left\">\n");
      out.write("\t\t\t\t\t\t<span class=\"selectedpath\">相册目录</span>\n");
      out.write("\t\t\t\t\t\t<span ng-if=\"albumName!=undefined\">></span>\n");
      out.write("\t\t\t\t\t\t<!--<span class=\"selectedpath\">首页图库</span> >-->\n");
      out.write("\t\t\t\t\t\t<span>{{albumName}}</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button class=\"fn-right\" id=\"addLeaf\">新建相册</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"album-content fn-clear\">\n");
      out.write("\t\t\t\t\t<div class=\"albumfile fn-left\" data-folderType=\"img\" ng-repeat=\"albumPic in albumPics\">\n");
      out.write("\t\t\t\t\t\t<img ng-src=\"{{albumPic.url}}\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t<p class=\"pt15\">{{albumPic.photoName}}</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"album-dia-bottom fn-clear\">\n");
      out.write("\t\t\t<div class=\"buttonbox fn-right mgr20\">\n");
      out.write("\t\t\t\t<button class=\"fn-left\" ng-click=\"closePostDia('album_dia')\">取消</button>\n");
      out.write("\t\t\t\t<button class=\"fn-left\" ng-click=\"postPictures()\">发布</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--选择发布的相册-->\n");
      out.write("\n");
      out.write("<!--图片预览蒙层-->\n");
      out.write("<div class=\"showScanImg\" id=\"showScanImg\">\n");
      out.write("\t<div style=\"position: relative;overflow-y: auto;width:100%;height:100%\">\n");
      out.write("\t\t<i class=\"fa fa-times-circle\" id=\"closeScanImg\" style=\"position:fixed; top:40px;right:40px;z-index:2\"></i>\n");
      out.write("\t\t<i class=\"fa fa-angle-left\" id=\"prevImg\" style=\"z-index: 2;\"></i>\n");
      out.write("\t\t<img src=\"\" alt=\"\" id=\"showImg\" />\n");
      out.write("\t\t<i class=\"fa fa-angle-right\" id=\"nextImg\" style=\"z-index: 2;\"></i>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--/图片预览蒙层-->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t//关闭分享、移动弹窗\n");
      out.write("\t$('.closeHandle').click(function(){\n");
      out.write("\t\t$('.handleDialog').hide();\n");
      out.write("\t});\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
