/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-27 03:33:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.productCenter.mapDepot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mapDepotDet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<a href=\"javascript:;\" class=\"line-btn forwardTop-goBack\" ng-click=\"gobackByRoute()\" ng-if=\"userInfo.orgType == '6'\">返回</a>\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<div class=\"content-wrapper content-wrapper-itemshow content-wrapper-itemshow2\">\n");
      out.write("\t<div class=\"forwardTop-content fn-left\" ng-if=\"userInfo.orgType == '6'\">\n");
      out.write("\t\t<div class=\"forwardTop-left\">\n");
      out.write("\t\t\t<img ng-src=\"{{orgInfo.shopLogo}}\" ng-if=\"orgInfo.shopLogo != '' \" />\n");
      out.write("\t\t\t<img src=\"http://static.qineasy.com/base/images/img_default_company.png\" ng-if=\"orgInfo.shopLogo == '' \" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"forwardTop-right\">\n");
      out.write("\t\t\t<div class=\"forwardTop-righttop\">\n");
      out.write("\t\t\t\t<p href=\"javascript:;\" class=\"forwardTop-rightTitl\">{{orgInfo.shopName}}</p>\n");
      out.write("\t\t\t\t<div class=\"fn-clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<p class=\"am-ft-black\">\n");
      out.write("\t\t\t\t<span class=\"stores-count\">店铺数：<a href=\"javascript:;\">{{orgInfo.shopNum}}个</a></span>\n");
      out.write("\t\t\t\t<span class=\"mgl10\">运营人员：{{orgInfo.userName}}<!-- <a href=\"javascript:;\"\n");
      out.write("\t\t\t\t\t\tclass=\"mgl5 allotOprate\">更换</a> --></span>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>联系电话：{{orgInfo.shopTel}}</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<span class=\"fn-left\">详细地址：{{orgInfo.province}}{{orgInfo.city}}{{orgInfo.district}}{{orgInfo.shopAddr}}</span>\n");
      out.write("\t\t\t\t<span class=\"fn-right am-ft-gray\">商户添加时间：{{orgInfo.openDate}}</span>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"ManColTable col-lg-12\">\n");
      out.write("\t\t<!--<div class=\"fn-clear\"></div>-->\n");
      out.write("\t\t<!-- <p class=\"am-ft-14 am-ft-black\">共{{countFolder}}个商品素材</p> -->\n");
      out.write("\t\t<div class=\"table-responsive  mgt15\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li class=\"folder-item\">\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" ng-click=\"getmateriaDetPub(this)\">\n");
      out.write("\t\t\t\t\t\t<img class=\"folderImg\" src=\"../static/base/images/icon_folder.png\" />\n");
      out.write("\t\t\t\t\t\t<p class=\"folderName\">公共图片</p>\n");
      out.write("\t\t\t\t\t\t<img class=\"imgPub-icon\" src=\"http://static.qineasy.com/base/images/imgPub.png\" />\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"folder-item\" ng-repeat=\"model in modelList\" ng-model=\"model\">\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" ng-click=\"getmateriaDetModel(this)\">\n");
      out.write("\t\t\t\t\t\t<img class=\"folderImg\" src=\"../static/base/images/icon_folder.png\" />\n");
      out.write("\t\t\t\t\t\t<p class=\"folderName\">{{model.proModelnum}}</p>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"fn-clear\"></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--分页 start-->\n");
      out.write("\t\t<div class=\"pagelist priv-pagelist\">\n");
      out.write("\t\t\t<div id=\"pagingFolder\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--分页 end-->\n");
      out.write("\t\t<!--<div class=\"fn-clear\"></div>-->\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"fn-clear\"></div>\n");
      out.write("\t<!--------------- /Content end ----------------->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
