/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-28 01:32:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pos.product.wdProduct;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class categoryMgt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"wrapper\" style=\"position: inherit;\">\r\n");
      out.write("<!--------------- Content start ----------------->\r\n");
      out.write("    <!--<div class=\"content-wrapper\" ng-hide=\"numA==1||numB==1||numC==1\">-->\r\n");
      out.write("    <div class=\"content-wrapper\" >\r\n");
      out.write("        <div class=\"col-md-11 pageTitl\">\r\n");
      out.write("            <h2 class=\"am-ft-16 fn-left\">品类列表</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fn-clear\"></div>\r\n");
      out.write("          <div class=\"proList-nav\" style=\"width: 67%;\">\r\n");
      out.write("            <div class=\"proTop\">\r\n");
      out.write("                <span class=\"fn-left\">品类列表</span>\r\n");
      out.write("                <!-- <button  type=\"button\" class=\"line-btn fn-right\" ng-click=\"toAddStandard('1')\">添加品类</button> -->\r\n");
      out.write("                <div class=\"fn-clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form id=\"wdProductListForm\">\r\n");
      out.write("                <table width=\"80%\" class=\"mgb0 table-hover table-condensed productTable\" id=\"wdProductList\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th  width=\"8%\"  align=\"center\" valign=\"middle\" scope=\"col\">品类名称</th>\r\n");
      out.write("                    <th  width=\"18%\"  align=\"center\" valign=\"middle\" scope=\"col\">品类属性</th>\r\n");
      out.write("                    <th  width=\"13%\"  align=\"center\" valign=\"middle\" scope=\"col\">品类规格</th>\r\n");
      out.write("                    <th   width=\"8%\" align=\"center\" valign=\"middle\" scope=\"col\">操作</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr ng-repeat=\"sortInfo in sortList\">\r\n");
      out.write("                    <td >\r\n");
      out.write("                       \t\t{{sortInfo.sortName}}\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>{{sortInfo.attrArr}}</td>\r\n");
      out.write("                    <td>{{sortInfo.itemList}}</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    \t<a href=\"javascripr:;\" class=\"am-ft-d4\" ng-click=\"editSort(this)\">编辑</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("              <!-- List end -->\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"fn-clear\"></div>\r\n");
      out.write("           </div>\r\n");
      out.write("             <!--分页 start\r\n");
      out.write("\t\t    <div class=\"pagelist priv-pagelist\" style=\"width: 92.5% !important;\">\r\n");
      out.write("\t\t    \t<div id=\"paging\"></div>    \r\n");
      out.write("\t\t    </div>-->\r\n");
      out.write("\t    <!--分页 end-->\r\n");
      out.write("    </div>    \r\n");
      out.write("    <!--------------- Content end ----------------->\n");
      out.write("</div>    \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
