/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-06-09 06:08:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tb.saleMgt.newSummary;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class newSummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--------------- Content start ----------------->\n");
      out.write("<style>\n");
      out.write("\t.laydate_table { \n");
      out.write("\t\tdisplay: none;\n");
      out.write("\t} \n");
      out.write("\t#laydate_hms{\n");
      out.write("\t\tdisplay: none!important;\n");
      out.write("\t}\n");
      out.write("\t.laydate_body .laydate_bottom .laydate_btn{\n");
      out.write("\t\ttop: 15px;\n");
      out.write("\t\tborder-right:none ;\n");
      out.write("\t}\n");
      out.write("\t.laydate_box{\n");
      out.write("\t\theight: 72px !important;\n");
      out.write("\t}\n");
      out.write("\t.laydate_body .laydate_bottom .laydate_btn a:last-child{\n");
      out.write("\t\tborder-right: 1px solid #DDDDDD;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\t\n");
      out.write("<!-- <a href=\"javascript:;\" class=\"line-btn forwardTop-goBack\" ng-if=\"type=='1'\" ng-click=\"gobWorkBench()\" >返回</a> -->\n");
      out.write("<div class=\"content-wrapper\tsaleSumary-wrapper fn-clear\">\n");
      out.write("\t<div class=\"firstTab col-lg-10 mgl20\" ng-if='childDepartCount>0'>\n");
      out.write("\t\t<ul class=\"fn-clear\">\n");
      out.write("\t\t\t<li class=\"fn-left\" ng-class=\"{true:'tabactive'}[productTab=='1']\" ng-click=\"shiftProductTab('1')\">部门汇总</li>\n");
      out.write("\t\t\t<li class=\"fn-left\" ng-class=\"{true:'tabactive'}[productTab=='2']\" ng-click=\"shiftProductTab('2')\">个人排行</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"col-lg-10  pl0 mgt5 mgl20 pr0 saleDetail\">\n");
      out.write("\t\t<div class=\"col-lg-12 paddinglr0\" >\n");
      out.write("\t\t\t<div class=\"searchByTime pdl20 pt10 pb10\">\n");
      out.write("\t\t\t\t<div class=\"fn-left mgr15 summary_laydate\">\n");
      out.write("\t\t\t\t\t<span>时间：</span>\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"start\" placeholder=\"开始日期\" ng-model='begindatea' class=\"mgr5 laydate-icon \"> ~\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"end\" placeholder=\"结束日期\"  ng-model='enddatea' class=\"mgl5  laydate-icon \" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"fn-left mgr15 \">\n");
      out.write("\t\t\t\t\t<span>产品类型：</span>\n");
      out.write("\t\t\t\t\t<select style=\"\" class=\"width120\" ng-model='taskType'>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">全部</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">套餐</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">客服</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">培训</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">运营</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">美工</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<button ng-click=\"searchData('1')\" ng-if=\"productTab=='1'\">查询</button>\n");
      out.write("\t\t\t\t<button ng-click=\"searchData('2')\" ng-if=\"productTab=='2'\">查询</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-lg-12 saleSummary mgl0 newSummary\" ng-if=\"productTab=='1'\">\n");
      out.write("\t\t\t<div class=\"bread_path summary_bread\" >\n");
      out.write("\t\t\t\t<span class=\"bread_nav\" >{{detailDate}}月各部门总销售业绩报表</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<table class=\"table saleSummaryDetail\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"45%\">部门</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">销售金额</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">新签金额</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">续签金额</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">提成金额</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">临时费用</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\" class=\"pd0 \">\n");
      out.write("\t\t\t\t\t\t<table class=\"summary_table table-border table-grand\">\n");
      out.write("\t\t\t\t\t\t\t<tr  ng-repeat='item in list'>\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"8\" class=\"pt0 pd0 table-border-bottom\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"mgb0 table-border table-son\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr ng-repeat='son in item.detailList'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td rowspan=\"{{item.detailList.length}}\" ng-if='$index==0' class=\"bg-ff\" scope=\"col\" width=\"17%\">{{item.departName}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"bg-ff\"  scope=\"col\" width=\"17%\">{{son.departName}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" class=\"pb0 pt0\" scope=\"col\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table class=\"mgb0 grandSon-bg table-border table-grandSon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr ng-repeat='grandSon in son.detailList'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" width=\"17%\">{{grandSon.departName}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" width=\"17%\">{{grandSon.serviceAmount}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" width=\"16.5%\">{{grandSon.newSignAmount}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" width=\"17%\">{{grandSon.reSignAmount}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" width=\"16.8%\">{{grandSon.deductAmout}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" >{{grandSon.extendAmount}}</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"summary_total\">\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"45%\">合计</td>\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"11%\" class=\"am-ft-orange\">{{sum.serviceAmount}}元</td>\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"11%\">{{sum.newSignAmount}}元</td>\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"11%\">{{sum.reSignAmount}}元</td>\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"11%\">{{sum.deductAmout}}元</td>\n");
      out.write("\t\t\t\t\t<td  scope=\"col\" width=\"11%\">{{sum.extendAmount}}元</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t\t<div class=\"col-lg-12 saleSummary mgl0 newSummary\" ng-if=\"productTab=='2'\">\n");
      out.write("\t\t\t<div class=\"bread_path summary_bread\" >\n");
      out.write("\t\t\t\t<span class=\"bread_nav\" >{{detailDate}}月个人销售排行榜</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<table class=\"table saleSummaryDetail\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">排名</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"11%\">姓名</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"16%\">部门</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"12%\">销售金额</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"12%\">新签金额</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"12%\">续签金额</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" width=\"12%\">提成金额</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\" >临时费用</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr ng-repeat='sign in rsListSign'>\n");
      out.write("\t\t\t\t\t<td>{{sign.num}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.trueName}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.departName}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.serviceAmount}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.newSignAmount}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.reSignAmount}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.deductAmout}}</td>\n");
      out.write("\t\t\t\t\t<td>{{sign.extendAmount}}</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<!--<tr>\r\n");
      out.write("\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t<td>张三</td>\r\n");
      out.write("\t\t\t\t\t<td>杭州商务一部</td>\r\n");
      out.write("\t\t\t\t\t<td>1000元</td>\r\n");
      out.write("\t\t\t\t\t<td>1000元</td>\r\n");
      out.write("\t\t\t\t\t<td>1000元</td>\r\n");
      out.write("\t\t\t\t\t<td>1000元</td>\r\n");
      out.write("\t\t\t\t\t<td>1000元</td>\r\n");
      out.write("\t\t\t\t</tr>-->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t\t<div class=\"col-md-12 pr0\" ng-if=\"productTab=='2'\">\r\n");
      out.write("\t\t\t<div id=\"paging\"></div>\r\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction removNext(a){\n");
      out.write("\t\t$(a).nextAll().remove();\n");
      out.write("\t}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
