/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-19 08:37:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pos.memberUnion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class memberUnion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--会员联盟首页-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.memberUnionList=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberUnionList.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--会员联盟首页-->\r\n");
      out.write("<!--创建会员联盟页面-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.memberUnionCreate=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberUnionCreate.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--创建会员联盟页面-->\n");
      out.write("<!--创建会员联盟成功-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.memberUnionCreateSuccess=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberUnionCreateSuccess.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--创建会员联盟成功-->\r\n");
      out.write("<!--加入会员联盟页面-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.memberUnionJoin=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberUnionJoin.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("<!--加入会员联盟页面-->\r\n");
      out.write("<!--加入会员联盟成功-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.memberUnionJoinSuccess=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberUnionJoinSuccess.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("<!--加入会员联盟成功-->\r\n");
      out.write("<!--加入会员联盟成功-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.showUnionMember=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "showUnionMember.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("<!--加入会员联盟成功-->\r\n");
      out.write("<!--在会员联盟页面点击设置积分规则-->\r\n");
      out.write("<div class=\"default\" ng-show=\"obj.IntegrationRule=='show'\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "IntegrationRule.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\t\r\n");
      out.write("<!--在会员联盟页面点击设置积分规则-->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
